var Eparameter_type={numeric:1,select:2,checkbox:3};function Cparameter(a){if(!a)return null;this.bAutosave=!0;this.parent=a.parent;this.type=a.type;this.def=a.def;this.label=a.label;if(!a.parent)return console.error("Ctool_parameter require parent in options {...}"),null;a.type||(a.type=Eparameter_type.numeric);this.init(a);this._init(a);return this}
Cparameter.prototype._init=function(a){if(this.bAutosave){var d=this.make_registry_key();10<SHOJS_DEBUG&&console.log("Loading parameter",d);d=cRegistry.get(d);void 0!=d?this._set(d):this._set(this.def)}else this._set(this.def);this.rootElm=null;d=/^callback_(.*)$/;for(k in a)d.exec(k)&&(a[k]&&"function"==typeof a[k])&&(10<SHOJS_DEBUG&&console.log("Installing callback for parameter["+this.type+"]",k),this[k]=a[k])};
Cparameter.prototype.set=function(a){if(this.value==a)return!1;this._set(a);this.bAutosave&&(a=this.make_registry_key(),cRegistry.set(a,this.value));return!0};Cparameter.prototype.reset=function(){this.set(this.def)};Cparameter.prototype._get=function(a){return a};Cparameter.prototype.dom_get=function(a){return this.rootElm&&void 0!=a&&!a?this.rootElm:this.dom_build().rootElm};
Cparameter.prototype.make_registry_key=function(){this.parent.className||console.log("parent",this.parent);this.parent.label||console.log("parent",this.parent);return((this.parent.className||"global")+"-"+(this.parent.label||"test")+"-"+this.label).toLowerCase()};function Cparameter_select(a){a.type=Eparameter_type.select;Cparameter.call(this,a)}Cparameter_select.prototype=Object.create(Cparameter.prototype);Cparameter_select.prototype.constructor=new Cparameter;Cparameter_select.prototype.init=function(a){this.choices={};this.def=a.def;this.label=a.label;for(label in a.choices)this.choices[label]=a.choices[label]};Cparameter_select.prototype._set=function(a){this.value=a};
Cparameter_select.prototype.dom_build=function(){var a=this,d=$(document.createElement("div"));d.addClass("selectex parameter");d.append("<h6>"+this.label+"</h6>");var e=$("<select />");for(c in this.choices){var f=$("<option/>");f.attr("value",this.choices[c]);this.value==this.choices[c]&&f.attr("selected","selected");f.append(document.createTextNode(this.choices[c]));e.append(f)}e.change(function(){a.set(this.value);a.rootElm.find("option").each(function(){$(this)});"callback_change"in a&&a.callback_change.call(a,
this.value)});d.append(e);this.rootElm=d;return this};function Cparameter_checkbox(a){a.type=Eparameter_type.checkbox;Cparameter.call(this,a)}Cparameter_checkbox.prototype=Object.create(Cparameter.prototype);Cparameter_checkbox.prototype.constructor=new Cparameter;Cparameter_checkbox.prototype.init=function(){this.choices={}};Cparameter_checkbox.prototype._get=function(a){return"true"==a?!0:"false"==a?!1:a?!0:!1};
Cparameter_checkbox.prototype._set=function(a){"false"==a||!a?(this.value=!1,this.rootElm&&this.rootElm.find("input").removeAttr("checked")):(this.value=!0,this.rootElm&&this.rootElm.find("input").attr("checked","checked"))};
Cparameter.prototype.dom_build=function(){var a=this,d=$("<div />");d.addClass("selectex parameter");d.append("<h6>"+this.label+"</h6>");var e=$("<input />");e.attr("type","checkbox");e.attr("title",label);this.value&&(e[0].checked="checked");e.change(function(){a.set(this.checked);"callback_change"in a&&a.callback_change.call(a,e[0].checked)});d.append(e);this.rootElm=d;return a};function Cparameter_numeric(a){a.type=Eparameter_type.numeric;Cparameter.call(this,a);return this}Cparameter_numeric.prototype=Object.create(Cparameter.prototype);Cparameter_numeric.prototype.constructor=new Cparameter;Cparameter_numeric.prototype.init=function(a){this.checks=Object({label:1,min:1,max:1,def:1,step:1});for(k in this.checks){if(!(k in a)||void 0===a[k])return console.error("Missing parameter key/value",a,k),null;this[k]="label"==k?a[k]:parseFloat(a[k])}};
Cparameter_numeric.prototype._get=function(a){return parseFloat(a)};Cparameter_numeric.prototype._set=function(a){this.value=a=parseFloat(a)};
Cparameter_numeric.prototype.dom_build=function(){var a=this,d=$("<div />");d.addClass("sliderex parameter "+this.label);d.attr("title",this.label);var e=$("<table />"),f=$("<tr />"),h=$("<td />");h.append("<h6>"+this.label+"</h6>");f.append(h);var i=$("<div />");i.addClass("slider");i.slider({min:this.min,max:this.max,value:this.value,step:this.step,slide:function(){var d=$(this),e=d.slider("option","value");a.set(e);d.parents(".sliderex").find("input.input").attr("value",e);"callback_slide"in a&&
a.callback_slide.call(a,e)},change:function(){var d=$(this),e=d.slider("option","value");a.set(e);d.parents(".sliderex").find("input.input").attr("value",e);"callback_change"in a&&a.callback_change.call(a,e)}});h=$("<td />");h.append(i);f.append(h);i=$("<input />");i.addClass("input");i.attr("value",this.value);i.css("width: 2em");i.change(function(){var d=$(this),e=d.attr("value");d.parents(".sliderex").find(".slider").slider("option","value",e);a.set(e);"callback_change"in a&&a.callback_change.call(a,
e)});i.spinner();h=$("<td />");h.append(i);f.append(h);e.append(f);d.append(e);this.rootElm=d;return this};function Cobject(a,d){void 0!=a&&(this.parent=null,this.parameters={},this._class_init(a,d),this.init())}Cobject.prototype._class_init=function(a,d){this.uid=UID.get();10<SHOJS_DEBUG&&console.log("UID",this.uid);this.parse_options(a,d)};
Cobject.prototype.parse_options=function(a,d){if(void 0==a)console.warn("No << {} >> argument passed to new Cobject");else{for(var d=d||[],e=["className","label"],f=0;f<e.length;f++){if(!(e[f]in a)&&!a[e[f]])return console.error("Missing "+e[f]+" in Cobject parameters"),!1;d.push(e[f])}if(d&&"object"===typeof d)for(f=0;f<d.length;f++)e=d[f],e in a?this[e]=a[e]:10<SHOJS_DEBUG&&console.warn("Needed property <<",e,">> ");if("parameters"in a)for(plabel in a.parameters)this.add_parameter(a.parameters[plabel]);
return!0}};Cobject.prototype.guid=function(a,d){return(""+this.className+"-"+this.uid+(d?"-"+d:"")).toLowerCase()};Cobject.prototype.get_trigger_name=function(a){return this.guid("trigger",a)};Cobject.prototype.send_trigger=function(a,d){var e=this.get_trigger_name(a);4<SHOJS_DEBUG&&console.log("[trigger/send]",e);$(document).trigger(e,d)};
Cobject.prototype.bind_trigger=function(a,d,e){a=a.get_trigger_name(d);4<SHOJS_DEBUG&&console.debug("[trigger/bind]",this.className," => ",a);$(document).bind(a,function(a,d){e.call(this,a,d)})};
Cobject.prototype.add_parameter=function(a){"parent"in a||(a.parent=this);if(!("label"in a))return console.error("Parameters need label"),!1;!("type"in a)||a.type==Eparameter_type.numeric?this.parameters[a.label]=new Cparameter_numeric(a):a.type==Eparameter_type.select?this.parameters[a.label]=new Cparameter_select(a):console.error("Unknown parameter type",a);return!0};
Cobject.prototype.get_parameter=function(a){return!("parameters"in this)||!(a in this.parameters)?(console.error("Invalid parameter <<",a,">>",this),null):this.parameters[a].value};Cobject.prototype.callback_exists=function(a){a="callback_"+a;return!(a in this)||"function"!=typeof this[a]?null:this[a]};Cobject.prototype.callback_get=function(a){a="callback_"+a;return!this.callback_exists(a)?null:this.options[a]};
Cobject.prototype.callback_execute=function(a){a="callback_"+a;this.callback_exists(a)&&console.error("No callback named "+a)};Cobject.prototype.init=function(){};Cobject.prototype.dom_get=function(a){return this.rootElm&&!a?this.rootElm:this.dom_build().rootElm};function Cpoint(a,d){this.x=a;this.y=d}function Cvector2d(a,d){Cpoint.call(this,a,d)}Cvector2d.prototype=Object.create(Cpoint.prototype);Cvector2d.prototype.constructor=new Cpoint;Cvector2d.prototype.magnitude=function(){return 0==this.x&&0==this.y?0:Math.sqrt(this.x*this.x+this.y*this.y)};Cvector2d.prototype.normalize=function(){var a=this.magnitude();if(0==a)return this;this.x/=a;this.y/=a;return this};Cvector2d.prototype.from_point=function(a,d){this.x=d.x-a.x;this.y=d.y-a.y;return this};
Cvector2d.prototype.smul=function(a){this.x*=a;this.y*=a;return this};Cvector2d.prototype.vadd=function(a){this.x+=a.x;this.y+=a.y;return this};Cvector2d.prototype.clone=function(){return new Cvector2d(this.x,this.y)};
var cMath={distance:function(a,d){var e=d.x-a.x,f=d.y-a.y;return Math.sqrt(e*e)+f*f},isint:function(a){return"number"===typeof a&&0==a%1},linear_interpolation:function(a,d,e){var f=[],h=new Cvector2d;h.from_point(a,d);var i=h.magnitude();if(0==i)return f;h.normalize();var j=a.clone();h.smul(e);f.push(a);for(a=0;a<=i;a+=e)j.vadd(h),f.push(new Cpoint(j.x,j.y));f.push(d);return f},clamp:function(a,d,e){return a<d?d:a>e?e:a}};function callback_stub(){}function helper_get_classname(a){return"undefined"===typeof a?"undefined":null===a?"null":Object.prototype.toString.call(a).match(/^\[object\s(.*)\]$/)[1]}function helper_bound_value(a,d,e){a<=d?a=d:a>=e&&(a=e);return Math.floor(a)}var near_zero_tolerance=0.01;function near_zero(a){return a<near_zero_tolerance&&a>-near_zero_tolerance?!0:!1}function helper_format_number_length(a,d){for(var e=""+a;e.length<d;)e="0"+e;return e}
function isCanvasSupported(){var a=document.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))}function isFileSupported(){if(window.File&&window.FileReader&&window.FileList&&window.Blob)return!0;console.error("The File APIs are not fully supported in this browser.")}function getObjectClass(a){if("object"!=typeof a||null===a)return!1;console.log(a.constructor.toString());return/^function (\w+)\(/.exec(a.constructor.toString())[1]};var SHOJS_DEBUG=1;function Cuid(){this.prefix="";this.id=null;this.stats={count:{label:"Number of UID generated",type:"int",value:0}};this.init()}Cuid.prototype.get_frag=function(){var a=Math.round(Math.random()*Date.now()/655350),a=parseInt((a+"").slice(0,5));return helper_format_number_length(a,5)};
Cuid.prototype.get=function(a){this.stats.count.value++;void 0==a&&(a=3);for(var d="",e=0;2>e;e++)d+=this.get_frag()+"-";d+="";if(document.getElementById(d)){console.error("UID already present in dom");a--;if(0<=a)return this.get(a);console.error("Cannot make unique uid... aborting!");return"UID_ERROR"}return d};Cuid.prototype.init=function(){this.id=this.get()};var UID=new Cuid;function Cdraw_glob(){this.graphing_interval=5}var DRAWGLOB=new Cdraw_glob;var Eloading_status={none:1,loading:2,fail:3,ok:4};function Cimage(a){a.className="Cimage";a.label="image";Cobject.call(this,a,[]);this.options=a;this.data=null;this.status=Eloading_status.none;this.errorMsg="";this.last_update=null;this.is_pushed=!1;this.dom_get()}Cimage.prototype=Object.create(Cobject.prototype);Cimage.prototype.constructor=new Cobject;
Cimage.prototype.dom_build=function(a,d){var e=this,f=this.options;if(this.rootElm&&!d)return console.warn("Image already loaded"),this;var h=a;"src"in f&&f.src&&(h=f.src);if(!h)return console.warn("No source for image"),!1;h=$("<img/>");h.onload=function(){e.callback_onload()};h.onerror=function(){e.callback_onerror()};"label"in f&&void 0!=f.label&&(h.attr("alt",this.options.label),h.attr("title",this.options.label));"width"in f&&void 0!=f.width&&h.attr("width",f.width);"height"in f&&void 0!=f.height&&
h.attr("height",f.height);"src"in f&&f.src&&h.attr("src",f.src);h.click(function(){e.callback_click()});this.rootElm=h;return this};
Cimage.prototype.callback_onload=function(){var a=!0;this.status=Eloading_status.ok;this.last_update=Date.now();if("replace_id"in this.options&&this.options.replace_id){var d=document.getElementById(this.options.replace_id);d?("label"in this.options&&d.setAttribute("alt"),d.width=this.data.width,d.height=this.data.height,d.src=this.data.src):(this.errorMsg="Replacing image failed",a=!1)}"callback_onload"in this.options&&"function"===typeof this.options.callback_onload&&!this.options.callback_onload.call(this,
this)&&(this.errorMsg+="Error while calling onload callback",a=!1);return a};Cimage.prototype.callback_onerror=function(){var a=!0;this.status=Eloading_status.fail;this.last_update=null;"callback_onerror"in this.options&&"function"===typeof this.options.callback_onerror&&!this.options.callback_onerror(this)&&(this.errorMsg+="Error while calling onerror callback",a=!1);return a};
Cimage.prototype.callback_click=function(){var a=!0;this.is_pushed=this.options.auto_release?!1:this.is_pushed?!1:!0;"callback_click"in this.options&&"function"===typeof this.options.callback_click&&!this.options.callback_click.call(this,this)&&(this.errorMsg+="Error while calling click callback",a=!1);return a};var Ecolor={transparent_black:"rgba(0,0,0,0)"};function Ccolor(a,d,e,f){this.r=a;this.g=d;this.b=e;this.a=f}Ccolor.prototype.to_rgba=function(){return"rgba("+this.r+","+this.g+","+this.b+","+this.a+")"};Ccolor.prototype.set_rgb=function(a){this.r=a.r;this.g=a.g;this.b=a.b;this.a=1;return this};Ccolor.prototype.set=function(a,d){if(a in this)return this[a]=d,this;console.error("Invalid key",a);return null};
Ccolor.prototype.from_rgba=function(a){var d=RegExp(/^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+(\.\d+)?)\s*\)$/).exec(a);if(!d)return console.error("Invalid rgba expression: "+a),this;this.r=d[1];this.g=d[2];this.b=d[3];this.a=d[4];return this};Ccolor.prototype.inverse=function(){var a=1/255;this.r=Math.round(255*(1-this.r*a));this.g=Math.round(255*(1-this.g*a));this.b=Math.round(255*(1-this.b*a));return this};
Ccolor.prototype.from_pixel=function(a,d,e){var f=a.data;this.r=f[d*4*a.width+4*e];this.g=f[d*4*a.width+4*e+1];this.b=f[d*4*a.width+4*e+2];this.a=f[d*4*a.width+4*e+3];this.a=Math.round(100*(this.a/255))/100;return this};Ccolor.prototype.clone=function(){return new Ccolor(this.r,this.g,this.b,this.a)};Ccolor.prototype.equal=function(a){for(var d=["a","r","g","b"],e,f=0;f<d.length;f++)if(e=d[f],this[e]!=a[e])return!1;return!0};
Ccolor.prototype.magnitude=function(){return Math.sqrt(this.r*this.r+this.g*this.g+this.b*this.b)};Ccolor.prototype.normalize=function(){var a=this.magnitude();this.r/=a;this.b/=b;this.g/=g;return this};function Ccanvas(a){a||console.error("Missing << {} >> parameter for Ccanvas");if(!("bg_color"in a)||!(a.bg_color instanceof Ccolor))a.bg_color=new Ccolor(0,0,0,0);a.className="Ccanvas";a.label="canvas";Cobject.call(this,a,["width","height","bg_color","src"]);this.data=document.createElement("canvas");this.data.setAttribute("width",this.width);this.data.setAttribute("height",this.height);this.ctx=this.data.getContext("2d");this.clear(this.bg_color);this.src&&this.load(this.src)}
Ccanvas.prototype=Object.create(Cobject.prototype);Ccanvas.prototype.constructor=new Cobject;Ccanvas.prototype.clone=function(){var a=new Ccanvas({width:this.width,height:this.height,bg_color:this.bg_color});a.copy(this);return a};Ccanvas.prototype.get_width=function(){return this.data.width};Ccanvas.prototype.get_height=function(){return this.data.height};
Ccanvas.prototype.copy=function(a,d){var e=this.data.getContext("2d");if("undefined"!=d&&d)e.drawImage(a.data,0,0,a.get_width(),a.get_height(),0,0,this.get_width(),this.get_height());else{var f=a.get_width()>this.get_width()?this.get_width():a.get_width(),h=a.get_height()>this.get_height()?this.get_height():a.get_height(),i=this.get_width()>f?(this.get_width()-f)/2:0,j=this.get_height()>h?(this.get_height()-h)/2:0;e.drawImage(a.data,0,0,f,h,i,j,f,h)}};
Ccanvas.prototype.get_pixel_color=function(a,d,e,f){return a.data[d*4*a.width+4*e+f]};Ccanvas.prototype.getCanvas=function(){return this.data};Cobject.prototype.getContext=function(a){a=a||"2d";if("data"in this)return this.data.getContext(a);console.error("Cannot return context for this object... no cCanvas");return null};
Ccanvas.prototype.clear=function(a){var a=a||new Ccolor(0,0,0,0),d=this.getContext();0==a.a?d.clearRect(0,0,this.data.width,this.data.height):(d.save(),d.fillStyle=a.to_rgba(),d.fillRect(0,0,this.data.width,this.data.height),d.restore())};Ccanvas.prototype.save=function(){var a=this.data.toDataURL("image/png");window.open(a)||(document.location.href=a)};var Ergb_color={red:0,green:1,blue:2,alpha:3};
Ccanvas.prototype.select_by_color=function(a){console.log("Selecting by color",a);var d=this.ctx.getImageData(0,0,this.data.width,this.data.height);this.ctx.save();this.ctx.beginPath();var e=0,f=d.width,h=d.height,i=document.createElement("canvas");i.width=f;i.height=h;var j=i.getContext("2d");j.fillStyle="rgba(0,0,0,1)";j.clearRect(0,0,f,h);j.translate(-0.5,-0.5);for(var l=0;l<h;l+=1)for(var m=0;m<f;m+=1)Math.round(100*(this.get_pixel_color(d,l,m,Ergb_color.alpha)/255))/100==a.a&&(this.get_pixel_color(d,
l,m,Ergb_color.red)==a.r&&this.get_pixel_color(d,l,m,Ergb_color.green)==a.g&&this.get_pixel_color(d,l,m,Ergb_color.blue)==a.b)&&(j.save(),j.translate(m,l),j.fillRect(0,0,1,1),j.restore(),e++);console.log("total line",e,[]);new Ccanvas(f,h,new Ccolor(0,0,0,1));this.ctx.clearRect(0,0,f,h);this.ctx.drawImage(i,0,0,f,h);this.ctx.restore()};
Ccanvas.prototype.to_bitmask=function(a){console.log(a);var d,e,f,h;a?(d=a,f=a.getContext("2d"),e=f.getImageData(0,0,a.width,a.height),h=a.width,a=a.height):(d=this.data,f=this.ctx,e=this.ctx.getImageData(0,0,this.data.width,this.data.height),h=this.data.width,a=this.data.heignt);var i=null;f.save();f.fillStyle="rgba(0,1,1,1)";f.clearRect(0,0,h,a);f.translate(-0.5,-0.5);for(var j=0;j<a;j+=1)for(var l=0;l<h;l+=1)i=this.get_pixel_color(e,j,l,Ergb_color.alpha)/255,f.save(),f.translate(l,j),1==i?f.clearRect(0,
0,1,1):f.fillRect(0,0,1,1),f.restore();f.restore();this.ctx.clearRect(0,0,this.data.width,this.data.height);this.ctx.drawImage(d,0,0,h,a)};
Ccanvas.prototype.load=function(a){var d=this;this.image_loading=new Cimage({src:a,callback_onload:function(){console.log("Image loaded",this);var a=cMath.clamp(1,this.rootElm.width,d.data.width),f=cMath.clamp(1,this.rootElm.height,d.data.height);d.data.getContext("2d").drawImage(this.rootElm,0,0,a,f);d.image_loading=null},callback_onerror:function(){console.log("Failed to load image",this);d.image_loading=null}})};Ccanvas.prototype.dom_build=function(){this.rootElm=this.data;return this};function Cregistry(){this.store=null;this.localStorage=new Clocal_storage;this.store=this.localStorage.store?this.localStorage.store:[]}Cregistry.prototype.set=function(a,d){this.store[a]=d;return this};Cregistry.prototype.get=function(a){return this.store[a]};Cregistry.prototype.get_set=function(a,d){var e;this.store[a+"_default"]=d;return(e=this.get(a))?e:this.store[a]=d};function Cminmax(a,d){this.min=a;this.max=d;this.last=null}Cminmax.prototype.init=function(a){this.min=this.max=this.last=a};Cminmax.prototype.cmp=function(a){if(void 0==a)return console.warn("MinMax: Comparing with null value"),!1;a<this.min&&(this.min=a);a>max&&(this.max=a);this.last=a;return!0};function Cmouse_tracker_point(a,d){Cvector2d.call(this,a,d);this.x=a;this.y=d;this.time=Date.now()}Cmouse_tracker_point.prototype=Object.create(Cvector2d.prototype);
Cmouse_tracker_point.prototype.constructor=new Cvector2d(0,0,0);
function Cmouse_tracker(a){a.className="Cmouse_tracker";a.label="mousetracker";Cobject.call(this,a,["parent","callback_move","callback_track"]);this.y=this.x=0;this.cMinmaxX=new Cminmax(0,this.parent.width);this.cMinmaxY=new Cminmax(0,this.parent.height);this.minmax=Object({minx:0,maxx:this.parent.width,miny:0,maxy:this.parent.height});this.minx=this.minmax.maxx;this.maxx=0;this.miny=this.minmax.maxy;this.maxy=0;this.pushed=null;this.paused=!1;this.interval=null;this.points=[];this.rootElm=null;return this}
Cmouse_tracker.prototype=Object.create(Cobject.prototype);Cmouse_tracker.prototype.constructor=new Cobject;Cmouse_tracker.prototype.reset=function(){this.minx=this.minmax.maxx;this.maxx=0;this.miny=this.minmax.maxy;this.maxy=0;this.points=[]};Cmouse_tracker.prototype.move=function(a,d){a=cMath.clamp(Math.round(a),this.minmax.minx,this.minmax.maxx);d=cMath.clamp(Math.round(d),this.minmax.miny,this.minmax.maxy);this.x=a;this.y=d;"callback_track"in this&&this.callback_track.call(this,a,d);return this};
Cmouse_tracker.prototype.push=function(){this.pushed=Date.now();var a=this;this.interval=setInterval(function(){if(!a.is_pushed())return clearInterval(a.interval),null;if(this.paused)return null;var d=new Cmouse_tracker_point(a.x,a.y);a.points.push(d);a.minx=Math.min(a.minx,d.x);a.maxx=Math.max(a.maxx,d.x);a.miny=Math.min(a.miny,d.y);a.maxy=Math.max(a.maxy,d.y)},DRAWGLOB.graphing_interval);this.func_push&&this.func_push(this)};
Cmouse_tracker.prototype.dom_build=function(){var a=$("<div />");a.attr("title","Mouse tracker");a.addClass("mousetracker");var d=document.createElement("div"),d=$(d);d.addClass("ui-widget-content");d.append('<div class="hold-var"><h6>x:&nbsp;</h6><span class="var-x">'+this.x+"</span></div>");d.append('<div class="hold-var"><h6>y:&nbsp;</h6><span class="var-y">'+this.y+"</span></div>");a.append(d);this.rootElm=a;return this};
Cmouse_tracker.prototype.release=function(){this.pushed=null;this.func_release&&this.func_release(this);this.reset()};Cmouse_tracker.prototype.is_pushed=function(){return this.pushed};Cmouse_tracker.prototype.to_s=function(){return"Cmouse_tracker: "+this.x+" / "+this.y};function Cwidget(a,d){Cobject.call(this);this.label=d;this.parent=a;this.dom=null}Cwidget.prototype=Object.create(Cobject.prototype);Cwidget.prototype.constructor=new Cobject;Cwidget.prototypeedom_get=function(a){return this.dom&&!a?this.dom:this.dom_build().dom};function Cwidget_window_header(a,d){Cwidget.call(this,a,d)}Cwidget_window_header.prototype=Object.create(Cwidget.prototype);Cwidget_window_header.prototype.constructor=new Cwidget;
Cwidget_window_header.prototype.dom_build=function(){var a=$(document.createElement("div"));a.addClass("window-header");a.append(this.label);this.dom=a;return this};function Cwidget_window(a,d){Cwidget.call(this,a,d);this.wHeader=new Cwidget_window_header(this,d)}Cwidget_window.prototype=Object.create(Cwidget.prototype);Cwidget_window.prototype.constructor=new Cwidget;
Cwidget_window.prototype.dom_build=function(){var a=$(document.createElement("div"));a.addClass("widget-window");a.append(this.wHeader.dom_get());this.dom=a;return this};var WM=new Cwidget_window;var CTOOL_brushes={circle:{update:function(){var a=this.parent.fg_color.color.clone(),d=this.parent.selected;d&&"opacity"in d.parameters&&(a.a=d.parameters.opacity.value);d=this.cCanvas.data.width/2;this.cCursor=new Ccanvas({width:this.cCanvas.width,height:this.cCanvas.height});cDraw.circle({dcanvas:this.cCursor.data,x:d,y:d,r:d,fillStyle:new Ccolor(255,0,0,0.4),strokeStyle:new Ccolor(255,0,0,1),lineWidth:1});cDraw.circle({dcanvas:this.cCanvas.data,x:d,y:d,r:d,fillStyle:a})},rectangle:function(){}}},
Ecomposite_operation={"source-over":"source-over","source-in":"source-in","source-out":"source-out","source-atop":"source-atop",lighter:"lighter",xor:"xor","destination-over":"destination-over","destination-in":"destination-in","destination-out":"destination-out","destination-atop":"destination-atop",darker:"darker"},CTOOL_tools={pen:{label:"pen",parameters:{size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},linecap:{type:Eparameter_type.select,label:"linecap",
choices:{round:"round",butt:"butt",square:"square"},def:"round"}},brush:CTOOL_brushes.circle,_graph:function(a,d,e){a=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");a.save();a.lineWidth=Math.round(this.parameters.size.value);var f=this.parent.fg_color.color.clone();f.a=this.parameters.opacity.value;a.strokeStyle=f.to_rgba();a.lineCap=this.parameters.linecap.value;a.beginPath();a.moveTo(d.x,d.y);a.lineTo(e.x,e.y);a.stroke();a.closePath();a.restore();return!0}},brush:{label:"brush",
parameters:{size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},pression:{label:"pression",min:0.1,max:100,def:100,step:0.01}},brush:CTOOL_brushes.circle,_update:function(){return!0},_graph:function(a,d,e){var a=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),f=this.cCanvas.data,h=f.width/2,i=f.height/2;f.getContext("2d");var j=this.get_parameter("pression"),d=cMath.linear_interpolation(d,e,100/j);if(0>=d.length)return!1;
for(e=0;e<d.length;e++)a.save(),a.translate(d[e].x-h,d[e].y-i),a.drawImage(f,0,0,f.width,f.height),a.restore();return!0}},eraser:{label:"eraser",parameters:{size:{label:"size",min:1,max:100,def:20,step:1},pression:{label:"pression",min:0.1,max:100,def:100,step:0.01}},compositeOperation:Ecomposite_operation.xor,brush:CTOOL_brushes.circle,_update:function(){},_pregraph:function(){var a=this.parent.parent.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),d=this.parent.parent.layer_manager,
e;d.special_layers.stack_down&&(e=d.special_layers.stack_down.cCanvas.data,a.drawImage(e,0,0,e.width,e.height));e=d.selected.cCanvas.data;a.drawImage(e,0,0,e.width,e.height)},_graph:function(a,d,e){var f=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");a.cSurface.layer_manager.special_layers.prefrag.down_composite_operation=Ecomposite_operation["source-in"];f.globalCompositeOperation=Ecomposite_operation["destination-out"];var a=this.cCanvas.data,h=a.width/2,i=a.height/
2;a.getContext("2d");for(var j=this.get_parameter("pression")||100,d=cMath.linear_interpolation(d,e,100/j),e=0;e<d.length;e++)f.save(),f.translate(d[e].x-h,d[e].y-i),f.drawImage(a,0,0,a.width,a.height),f.restore();f.restore();return!0},_postgraph:function(a,d,e,f){var h=this.parent.parent.layer_manager.selected,i=this.parent.parent.layer_manager.special_layers.prefrag,j=i.clone();j.ctx.save();j.ctx.clearRect(0,0,j.cCanvas.data.width,j.cCanvas.data.height);j.ctx.globalCompositeOption="xor";j.ctx.drawImage(i.cCanvas.data,
0,0,i.cCanvas.data.width,i.cCanvas.data.height);h.drawImage(j.cCanvas.data,a,d,e,f,0,0,"source-in");j.ctx.restore()}}};function Ctool(a){this.cCanvas=this.brush=null;this.need_update=!0;this.optElm=this.rootElm=null;a.className="Ctool";this.changeCursor=!0;for(p in a.parameters)a.parameters[p].parent=this;Cobject.call(this,a,"parent brush label _pregraph _graph _postgraph _update compositeOperation".split(" "));return this}Ctool.prototype=Object.create(Cobject.prototype);Ctool.prototype.constructor=new Cobject;
Ctool.prototype.canvas_create=function(a,d){if(!a||0>a||1920<a)return console.error("Width not in range",a),null;if(!d||0>d||1080<d)return console.error("Height not in range",d),null;this.set_parameter("width",a);this.set_parameter("height",d)};Ctool.prototype.set_options=function(a){if(!a.brush)return console.error("No brush in Ctool options"),!1};
Ctool.prototype.update=function(){this.need_update=!0;if(!this.need_update)return console.log("Doesn't need update"),!1;var a=this.get_parameter("size");if(!a)return console.error("All tools need << size >> parameter"),!1;var d=a/2;this.cCanvas=new Ccanvas({width:a,height:a});this.ctx=this.cCanvas.getContext("2d");this.brush.update.call(this,this);"_update"in this&&this._update.call(this);this.changeCursor&&this.parent.parent.rootElm&&this.parent.parent.rootElm.find(".canvas").parent().css("cursor",
"url('"+this.cCursor.data.toDataURL()+"') "+d+" "+d+", auto");this.need_update=!1};Ctool.prototype.drawImage=function(a,d,e){var f=a.getContext("2d"),h=this.cCanvas.canvas;if(!f)return console.error("Cannot acquire context"),!1;if(d>a.width||0>d)return console.error("x not in canvas destination range",d),!1;if(e>a.height||0>e)return console.error("y not in canvas destination range",e),!1;f.drawImage(h,0,0,h.width,h.height,d,e,h.width,h.height);return!0};
Ctool.prototype.onclick=function(){"callback_onclick"in this.options&&"function"===typeof this.options.callback_onclick&&this.options.callback_onclick(this)};Ctool.prototype.dom_build=function(a){if(this.rootElm&&!a)return this;a=$("<div />");a.append(this.dom_build_tool());this.rootElm=a;return this};
Ctool.prototype.dom_build_tool=function(){var a=this,d=new Cimage({src:"img/32x32_tool_"+this.label+".png",callback_onload:function(){},callback_click:function(d){a.callback_click.call(a,d)},label:this.label});return $(d.dom_get())};Ctool.prototype.dom_build_options=function(){if(this.optElm)return this.optElm;var a=$(document.createElement("div"));a.addClass("not-draggable");for(label in this.parameters)a.append(this.parameters[label].dom_get());return this.optElm=a};
Ctool.prototype.callback_click=function(){this.parent&&this.parent.select_tool(this)};Ctool.prototype.graph=function(a,d,e){return this._graph(a,d,e)};function Clicense(){this.logo="img/gplv3-88x31.png";this.text="http://shojs.github.com/graphit/license-gpl3.txt";this.rootElm=null}
Clicense.prototype.dom_build=function(){if(this.rootElm)return this;var a=$('<div title="License"/>');a.addClass("about ");var d=$("<div />");d.addClass("group-license");var e=$("<img />");e[0].src=this.logo;d.append(e);d.append('<p>Source code: <a href="#code" onclick="window.open(\'http://github.com/shojs/graphit/\'); return false;">github</a></p>');d.append('<p>Documentation: <a href="#doc" onclick="window.open(\'http://github.com/shojs/graphit/wiki\');return false;">Wiki</a></p>');d.append("<h6>License</h6>");
e=$("<p />");e.addClass("text");e.append("                    GNU GENERAL PUBLIC LICENSE                       Version 3, 29 June 2007\n\n Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.\n\n                            Preamble\n  The GNU General Public License is a free, copyleft license forsoftware and other kinds of works.\n\n  The licenses for most software and other practical works are designedto take away your freedom to share and change the works.  By contrast,the GNU General Public License is intended to guarantee your freedom toshare and change all versions of a program--to make sure it remains freesoftware for all its users.  We, the Free Software Foundation, use theGNU General Public License for most of our software; it applies also toany other work released this way by its authors.  You can apply it toyour programs, too.\n\n  When we speak of free software, we are referring to freedom, notprice.  Our General Public Licenses are designed to make sure that youhave the freedom to distribute copies of free software (and charge forthem if you wish), that you receive source code or can get it if youwant it, that you can change the software or use pieces of it in newfree programs, and that you know you can do these things.\n  To protect your rights, we need to prevent others from denying youthese rights or asking you to surrender the rights.  Therefore, you havecertain responsibilities if you distribute copies of the software, or ifyou modify it: responsibilities to respect the freedom of others.");
d.append(e);try{e.load(this.text)}catch(f){console.error("Cannot load full license",f)}e=document.createElement("button");$(e).append("Close");$(e).button();$(e).click(function(){$(".about").remove()});d.append(e);a.append(d);this.rootElm=a;return this};Clicense.prototype.dom_get=function(){return this.dom_build().rootElm};var Egrapher_mode={continuous:1,endpoint:2};function Cgrapher(a,d){Cobject.call(this,{className:"Cgrapher",label:"grapher",cToolbox:a,cSurface:d},["label","cToolbox","cSurface"]);this.reset_index();this.timer=null;this.mode=Egrapher_mode.continuous}Cgrapher.prototype=Object.create(Cobject.prototype);Cgrapher.prototype.constructor=new Cobject;Cgrapher.prototype.reset_index=function(){this.index=0};
Cgrapher.prototype._graph=function(){var a=this.cSurface.cMouse.points.length;if(2>=a||this.index>=a-1)return!1;this.cToolbox.selected.graph(this,this.cSurface.cMouse.points[this.index],this.cSurface.cMouse.points[this.index+1])&&this.cSurface.redraw(!0);this.index++;this._graph();return!0};
Cgrapher.prototype.stop=function(){if(!this.timer)return console.warn("Grapher is not started"),!1;clearInterval(this.timer);this.timer=null;var a=this.cSurface,d=a.layer_manager.selected.cCanvas.data,e=this.cToolbox.selected.parameters.size.value,f=e/2,h=a.cMouse.maxx-a.cMouse.minx+e,e=a.cMouse.maxy-a.cMouse.miny+e,i=a.cMouse.minx-f;0>i&&(i=0);i+h>d.width&&(h=d.width-i);f=a.cMouse.miny-f;0>f&&(f=0);f+e>d.height&&(e=d.height-f);"_postgraph"in this.cToolbox.selected?this.cToolbox.selected._postgraph(i,
f,h,e,0,0,h,e):a.layer_manager.selected.drawImage(a.layer_manager.special_layers.prefrag.cCanvas.data,i,f,h,e,0,0);a.layer_manager.selected.redraw();a.layer_manager.special_layers.prefrag=new Clayer(a.layer_manager,"_prefrag");this.index=0;this.send_trigger("update");return!0};
Cgrapher.prototype.start=function(){if(this.timer)return console.error("Grapher already started"),!1;var a=this;if(!this.cToolbox||!this.cToolbox.selected)return this.send_trigger("error","no-tool-selectionned"),console.error("No tool selectionned!"),!1;"_pregraph"in this.cToolbox.selected&&this.cToolbox.selected._pregraph(this);this.timer=window.setInterval(function(){a._graph()},DRAWGLOB.graphing_interval);return!0};var cDraw={circle:function(a){var d=a.dcanvas.getContext("2d");if(!d)return console.error("Cannot aquiere context"),!1;d.save();d.beginPath();d.arc(a.x,a.y,a.r,0,2*Math.PI,!0);a.fillStyle&&(d.fillStyle=a.fillStyle.to_rgba(),d.fill());a.lineWidth&&(d.lineWidth=a.lineWidth);a.strokeStyle&&(d.strokeStyle=a.strokeStyle.clone().set("a",1).to_rgba(),d.stroke());d.closePath();d.restore();return!0}};function Cfrag(a){a.className="Cfrag";a.label="frag";Cobject.call(this,a,["parent","position","width","height","color"]);this.color||(this.color=new Ccolor(0,0,0,0));this.cCanvas=new Ccanvas({width:this.width,height:this.height,bg_color:this.color});this.ctx=this.getContext()}Cfrag.prototype=Object.create(Cobject.prototype);Cfrag.prototype.constructor=new Cobject;Cfrag.prototype.getContext=function(){return this.cCanvas.getContext("2d")};
Cfrag.prototype.drawImage=function(a,d,e,f,h){var i=this.cCanvas.data,j=this.cCanvas.data.getContext("2d");try{j.drawImage(a,d,e,f,h,0,0,i.width,i.height)}catch(l){return console.error("Cannot draw to fragment",l),!1}return!0};var E_DRAWCOMPOSITION=Object({"source-in":"source-in","source-over":"source-over"});
function Clayer(a,d,e){var f=this;e||(composiste_operation=Ecomposite_operation["source-over"]);Cobject.call(this,{className:"Clayer",parent:a,label:d,composite_operation:e,visible:!1,need_redraw:!0},["parent","label","composite_operation","need_redraw","visible"]);this.uid=UID.get();this.frags=[];this.cCanvas=new Ccanvas({width:a.parent.width,height:a.parent.height});this.ctx=this.cCanvas.getContext("2d");this.bind_trigger(this,"redraw_preview",function(a){4<SHOJS_DEBUG&&console.debug("[Trigger/received]",
a.type);f.redraw_preview()})}Clayer.prototype=Object.create(Cobject.prototype);Clayer.prototype.constructor=new Cobject;Clayer.prototype.clone=function(){var a=this.cCanvas.data,d=new Clayer(this.parent,this.label,this.composition);d.visible=this.visible;d.ctx.drawImage(a,0,0,a.width,a.height);d.need_redraw=!1;d.rootElm=this.rootElm;return d};Clayer.prototype.discard_frag=function(){this.need_redraw=!0;this.send_trigger("update");return this.frags.pop()};
Clayer.prototype.dom_get=function(){this.dom_build();return this.rootElm};Clayer.prototype.set_visibility=function(a){this.visibility=a?!0:!1};Clayer.prototype.toggle_visibility=function(){return!0==this.visibility?this.set_visibility(!1):this.set_visibility(!0)};
Clayer.prototype.dom_build=function(){if(this.rootElm)return this;var a=this,d=document.createElement("li"),e=$(d);e.attr("id",this.uid);e.addClass("layer");d=$("<div/>");d.attr("id",this.uid);var f=$("<ul />");f.append('<li><a href="#'+this.guid("tab",1)+'">layer</a></li>');f.append('<li><a href="#'+this.guid("tab",2)+'">option</a></li>');f.append('<li><a href="#'+this.guid("tab",3)+'">stats</a></li>');d.append(f);var f=$('<div id="'+this.guid("tab",1)+'"/>'),h=new Cimage({src:"img/16x16_eye.png",
width:"16px",height:"16px",callback_click:function(d){a.toggle_visibility();a.parent.send_trigger("update");console.log("Clicked: ",d)}}),i=document.createElement("table"),i=$(i),j=$(document.createElement("tr")),l=$(document.createElement("td"));l.append(h.dom_get());j.append(l);l=$(document.createElement("td"));h=$(document.createTextNode("Layer - "+this.label));l.append(h);l.editInPlace({callback:function(d,e){return a.label=e}});l.addClass("label");j.append(l);l=$(document.createElement("td"));
l.addClass("preview");this.canvas_preview=h=document.createElement("canvas");var m=100*(this.cCanvas.data.height/this.cCanvas.data.width);h.width=100;h.height=m;h=$(h);l.click(function(){$(this).parents(".group-layers").find(".layer").removeClass("selected");$(this).parents(".layer").addClass("selected");a.parent.select(a)});l.append(h);j.append(l);l=$(document.createElement("td"));h=new Cimage({src:"img/16x16_up.png",width:16,height:16,callback_click:function(){a.parent.move_up(a.uid)}});l.append(h.dom_get());
h=new Cimage({src:"img/16x16_down.png",width:16,height:16,callback_click:function(){a.parent.move_down(a.uid)}});l.append(h.dom_get());h=new Cimage({src:"img/16x16_trash.png",width:16,height:16,callback_click:function(){$(this).parents("li.layer")?(e.remove(),a.parent.remove(a)):console.error("Cannot remove layer element")}});j.append(l);l=$(document.createElement("td"));l.addClass("options");l.append(h.dom_get());j.append(l);i.append(j);f.append(i);d.append(f);f=$('<div id="'+this.guid("tab",2)+
'"/>');f.append("<p>Layer option</p>");d.append(f);var n=$('<div id="'+this.guid("tab",3)+'"/>');n.append('<p>Total fragment: <span id="'+this.guid("stat","total-fragment")+'">'+this.frags.length+"</span></p>");this.bind_trigger(this,"redraw_preview",function(){n.find("span").empty().append(a.frags.length)});d.append(n);e.append(d);d.tabs();this.rootElm=e;return this};
Clayer.prototype.redraw_preview=function(){var a=this.canvas_preview.getContext("2d"),d=this.cCanvas.data;a.clearRect(0,0,d.width,d.height);a.drawImage(d,0,0,d.width,d.height,0,0,this.canvas_preview.width,this.canvas_preview.height)};
Clayer.prototype.redraw=function(a){"boolean"===typeof a&&(this.need_redraw=a);if(!this.need_redraw)return!1;this.ctx.clearRect(0,0,this.cCanvas.data.width,this.cCanvas.data.height);"compositeOperation"in this&&(this.ctx.compositeOperation=this.compositeOperation);for(var a=this.cCanvas.data.width,d=this.cCanvas.data.height,e=0;e<this.frags.length;e++){var f=this.frags[e],h=f.cCanvas.data,i=h.height,j=h.width,l=f.position.x;0>l?l=0:l+j>a&&(j=a-l);var m=f.position.y;0>m?m=0:m+i>d&&(i=d-m);this.ctx.save();
this.ctx.beginPath();this.ctx.rect(l,m,j,i);this.ctx.clip();this.ctx.globalCompositeOperation=f.downCompositeOperation?f.downCompositeOperation:"source-over";this.ctx.drawImage(h,0,0,j,i,l,m,j,i);this.ctx.restore()}this.send_trigger("redraw_preview");this.need_redraw=!1;return!0};Clayer.prototype.clear=function(){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);this.frags=[]};Clayer.prototype.get_canvas=function(){this.redraw();return this.canvas};
Clayer.prototype.stack_frags=function(a,d){var e=a,f=d;a>d&&(e=d,f=a);for(var h=new Cdraw_frag(this.canvas.width,this.canvas.height),i=h.getContext("2d"),j=e;j<=f;j++){var l=this.frags[j],m=l.cCanvas.data;i.drawImage(m,0,0,m.width,m.height,l.position.x,l.position.y,m.width,m.height)}this.frags.splice(e,0,h);this.frags.splice(e,f)};
Clayer.prototype.drawImage=function(a,d,e,f,h,i,j,l){i=new Cfrag({parent:this,position:{x:d,y:e},width:f,height:h});i.drawImage(a,d,e,f,h,0,0);this.frags.push(i);l&&(this.ctx.globalCompositeOperation=l,i.downCompositeOperation=l);this.redraw()};Clayer.prototype.to_json=function(){return{label:this.data,data:this.cCanvas.data.toDataURL()}};function Clayer_manager(a){var d=this;Cobject.call(this,{parent:a,className:"Clayer_manager",label:"layermanager"},["parent","label"]);this.layers=[];this.special_layers={};this.selected=null;this.dom_build();this.bind_trigger(this,"update",function(){d.redraw()});this.add(new Clayer(this,"_stack_up"));this.add(new Clayer(this,"_stack_down"));this.add(new Clayer(this,"_grid"));this.add(new Clayer(this,"background"))}Clayer_manager.prototype=Object.create(Cobject.prototype);
Clayer_manager.prototype.constructor=new Cobject;Clayer_manager.prototype.layer_stack=function(a,d){if(a>d)return null;for(var e=new Clayer(this,"stack"),f,h=a;h<=d;h++)f=this.layers[h].cCanvas.data,e.ctx.drawImage(f,0,0,f.width,f.height);return e};Clayer_manager.prototype.build_layer_stack=function(a){this.special_layers.stack_down=this.layer_stack(0,a-1);this.special_layers.stack_up=this.layer_stack(a+1,this.layers.length-1)};
Clayer_manager.prototype.add=function(a){a.parent=this;if(!(a instanceof Clayer))return console.error("Layer manager need Clayer object"),null;var d=RegExp(/^_(.*)/).exec(a.label);d?(a.label="layer-"+d[1],this.special_layers[d[1]]=a):(a.label=this.layers.length,this.layers.push(a));if(!d&&this.rootElm){var d=$(this.rootElm).find(".group-layers"),e=$(a.dom_get(this.layers.length-1));d.prepend(e)}this.send_trigger("update");return a};
Clayer_manager.prototype.exists=function(a){for(var d=0,e=!1,d=0;d<this.layers.length;d++)if(this.layers[d]==a){e=!0;break}return e?d:null};Clayer_manager.prototype.remove=function(a){var d=this.selected,e=this.exists(a);d==a&&1<e&&(d=this.layers[e-1]);void 0===e&&console.error("Cannot remove undefined element");this.layers.splice(e,1);this.select(d);this.parent.redraw(!0)};Clayer_manager.prototype.get_layer=function(a){return cMath.isint(a)?this.layers[a]:this.special_layers[a]};
Clayer_manager.prototype.get_index_by_uid=function(a){for(var d=0;d<this.layers.length;d++)if(this.layers[d].uid==a)return d;return null};Clayer_manager.prototype.move_down=function(a){a=this.get_index_by_uid(a);if(void 0===a||1>=this.layers.length||1>a)return console.error("Can't move layer up"),!1;var d=this.layers[a-1];this.layers[a-1]=this.layers[a];this.layers[a]=d;this.select(this.selected);this._build_layer_preview(".group-layers");this.send_trigger("update");return!0};
Clayer_manager.prototype.move_up=function(a){if(1==this.layers.length)return!1;a=this.get_index_by_uid(a);if(void 0===a||a>=this.layers.length-1||1>=this.layers.length)return console.error("Can't move layer up"),!1;var d=this.layers[a+1];this.layers[a+1]=this.layers[a];this.layers[a]=d;this.select(this.selected);this._build_layer_preview(".group-layers");this.send_trigger("update");return!0};
Clayer_manager.prototype.select=function(a){a=this.exists(a);if(void 0===a||0>a||a>this.layers.length)return console.error("Layer index out of range: "+a),!1;this.build_layer_stack(a);this.selected=this.layers[a];this.send_trigger("update");return!0};
Clayer_manager.prototype.dom_build=function(a,d){if(!d&&this.rootElm)return this.rootElm;var e=this,f=$("<div />");f.attr("title","Layer manager");var h=$("<div />");$("<div />");var i=new Cimage({src:"img/16x16_create_file.png",width:16,height:16,title:"Create new layer",callback_click:function(){e.add(new Clayer(e))}});f.append(i.dom_get());i=$("<ul />");i.addClass("group-layers ui-widget-content");f.append(i);f.append(h);this.rootElm=f;return this};
Clayer_manager.prototype._build_layer_preview=function(a){a=$(a);a.find(".layer").detach();for(var d=this.layers.length-1;0<=d;d--)this.layers[d].redraw(!0),a.append(this.layers[d].dom_get(1))};Clayer_manager.prototype.dom_exists=function(a){var d=!1,e;for(e=0;e<this.layers.length;e++)if(this.layers[e].rootElm=a){d=!0;break}return d?e:null};Clayer_manager.prototype.redraw=function(a){for(var d=0;d<this.layers.length;d++)this.layers[d].redraw(a);this.send_trigger("redraw")};
Clayer_manager.prototype.dom_get=function(){this.dom_build();return this.rootElm};function Csurface(a,d,e){var f=this;Cobject.call(this,{className:"Csurface",label:"surface",width:d,height:e},["width","height","label"]);this.need_redraw=!1;this.cCanvas=new Ccanvas({width:this.width,height:this.height});this.cCanvas.clear(new Ccolor(0,0,0,1));this.cToolbox=new Ctoolbox(CTOOL_tools,{parent:this});this.cGrapher=new Cgrapher(this.cToolbox,this);this.bind_trigger(this.cGrapher,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);f.send_trigger("update")});this.layer_manager=
new Clayer_manager(this);this.layer_manager.add(new Clayer(this.layer_manager,E_LAYERLABEL.mouse));this.layer_manager.add(new Clayer(this.layer_manager,E_LAYERLABEL.prefrag));this.layer_manager.add(new Clayer(this.layer_manager));this.layer_manager.select(this.layer_manager.layers[0]);this.bind_trigger(this.layer_manager,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);f.send_trigger("update")});this.cMouse=new Cmouse_tracker({parent:this,callback_move:function(){console.log("mouse move")},
callback_track:function(a,d){$(f.cMouse.rootElm).find(".var-x").empty().append(a);$(f.cMouse.rootElm).find(".var-y").empty().append(d)}});this.cGrid=new Cgrid({parent:this,callback_slide:function(a){this.set(a);console.log("slide");this.send_trigger("update")},callback_change:function(a){this.set(a);console.log("Change");this.send_trigger("update")}});this.bind_trigger(this.cGrid,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);f.update_grid()});this.bind_trigger(this,
"update",function(){f.redraw()});this.update_grid()}Csurface.prototype=Object.create(Cobject.prototype);Csurface.prototype.constructor=new Cobject;Csurface.prototype.set_current_layer=function(a){this.layer_manager.select(a)};
Csurface.prototype.update_grid=function(){var a=this.layer_manager.get_layer("grid");a.cCanvas.getContext().clearRect(0,0,a.cCanvas.data.width,a.cCanvas.data.height);this.cGrid.get_parameter("visibility")&&this.cGrid.draw(a.cCanvas.data,0,0,this.cCanvas.data.width,this.cCanvas.data.height);this.need_redraw=!0;this.send_trigger("update")};
Csurface.prototype.dom_build=function(){var a=this,d=$('<div title="Surface"/>');d.addClass("surface");var e=$("<div/>"),f=$(this.cCanvas.data);f.width=this.width;f.height=this.height;f.addClass("canvas");f.mousedown(function(d){a.callback_mousedown(d,a)});f.mouseup(function(d){a.callback_mouseup(d,a)});f.mousemove(function(d){a.callback_mousemove(d,a)});f.mouseout(function(){a.cMouse.is_pushed()&&(a.cMouse.paused=!0)});f.mouseover(function(){a.cMouse.is_pushed()&&(a.cMouse.paused=!1)});e.append(f);
d.append(e);$(document).bind("keydown","Ctrl+z",function(){a.undo()});d.append(e);this.rootElm=d;return this};Csurface.prototype.undo=function(){this.layer_manager.selected.discard_frag();this.layer_manager.selected.redraw();this.redraw(!0)};
Csurface.prototype.redraw=function(a){if(!this.need_redraw&&!a)return!1;var d=this.cCanvas.data,e=d.getContext("2d");e.save();e.clearRect(0,0,d.width,d.height);void 0!=this.layer_manager.special_layers.stack_down&&e.drawImage(this.layer_manager.special_layers.stack_down.cCanvas.data,0,0,d.width,d.height);this.layer_manager.selected.redraw(a);e.drawImage(this.layer_manager.selected.cCanvas.data,0,0,d.width,d.height);"down_composite_operation"in this.layer_manager.special_layers.prefrag&&(e.globalCompositeOperation=
this.layer_manager.special_layers.prefrag.down_composite_operation);e.drawImage(this.layer_manager.special_layers.prefrag.cCanvas.data,0,0,d.width,d.height);"down_composite_operation"in this.layer_manager.special_layers.prefrag&&(e.globalCompositeOperation="source-over");void 0!=this.layer_manager.special_layers.stack_up&&e.drawImage(this.layer_manager.special_layers.stack_up.cCanvas.data,0,0,d.width,d.height);"cGrid"in this&&this.cGrid.isVisible&&e.drawImage(this.layer_manager.special_layers.grid.cCanvas.data,
0,0,d.width,d.height);e.restore();this.send_trigger("redraw");this.need_redraw=!1;return!0};Csurface.prototype.clear=function(){for(var a=0;a<this.layer_manager.layers.length;a++)this.layer_manager.layers[a].clear();this.need_redraw=!0;this.send_trigger("update")};Csurface.prototype.callback_mousedown=function(){if(this.cMouse.is_pushed())return console.warn("Mouse already pushed"),!1;this.cMouse.push();this.cGrapher.start();return!0};
Csurface.prototype.callback_mouseup=function(){if(!this.cMouse.is_pushed())return console.warn("Mouse not pushed"),!1;this.cGrapher.stop();this.redraw(!0);this.cMouse.release();return!0};Csurface.prototype.callback_mousemove=function(a,d){var e=$(d.cCanvas.data).offset();this.cMouse.move(a.pageX-e.left,a.pageY-e.top)};Csurface.prototype.save_as_json=function(){window.open(this.cCanvas.data.toDataURL());return data};function Cmetasurface(a){Cobject.call(this,a,[]);this.rootElm=this.cSurface=null;this.dom_get()}Cmetasurface.prototype=Object.create(Cobject.prototype);Cmetasurface.prototype.constructor=new Cobject;Cmetasurface.prototype.attach_surface=function(a){if(this.pSurface)return console.error("There is already a surface attached"),null;this.cSurface=a;this.rootElm.find(".metasurface-container").append(this.cSurface.dom_get());return this};
Cmetasurface.prototype.dom_build=function(){var a=$('<div title="Meta surface"/>'),d=$("<div />");d.addClass("metasurface-container");a.append(d);a.dialog({});this.rootElm=a;return this};function Cgrid(a){a.className="Cgrid";a.label="grid";Cobject.call(this,a,["parent","callback_slide","callback_change","label"])}Cgrid.prototype=Object.create(Cobject.prototype);Cgrid.prototype.constructor=new Cobject;
Cgrid.prototype.init=function(){this.color=this.color||new Ccolor(0,0,0,1);this.isVisible=this.isVisible||!0;var a=this,d=function(){a.send_trigger("update")};this.parameters={width:new Cparameter_numeric({parent:this,label:"width",min:1,max:100,def:100,step:1,callback_change:d,callback_slide:d}),height:new Cparameter_numeric({parent:this,label:"height",min:1,max:100,def:100,step:1,callback_change:d,callback_slide:d}),lineWidth:new Cparameter_numeric({parent:this,label:"lineWidth",min:1,max:10,def:1,
step:1,callback_change:d,callback_slide:d}),visibility:new Cparameter_checkbox({parent:this,type:Eparameter_type.checkbox,label:"visibility",def:!0,callback_change:d})};for(p in this.parameters)this.parameters[p]._init();this.label="grid";this.rootElm=null};
Cgrid.prototype.draw=function(a,d,e,f,h){d=a.getContext("2d");d.save();d.beginPath();f=this.get_parameter("width");h=this.get_parameter("height");for(e=f+1;e<a.width;e+=f)d.moveTo(e,0),d.lineTo(e,a.height);for(f=h+1;f<a.height;f+=h)d.moveTo(0,f),d.lineTo(a.width,f);d.closePath();d.strokeStyle=this.color.to_rgba();d.lineWidth=this.get_parameter("lineWidth");d.stroke();d.restore()};
Cgrid.prototype.dom_build=function(){var a=$("<div />");a.attr("title",this.label);a.addClass("grid");var d=$("<div />");d.addClass("ui-widget-content");for(label in this.parameters)a.append(this.parameters[label].dom_get());a.append(d);this.rootElm=a;return this};function Ctoolbox_preview(a){var d=this;a.className="Ctoolbox_preview";a.label="toolboxpreview";Cobject.call(this,a,["parent"]);this.bind_trigger(this.parent,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);d.rootElm.find("canvas")[0].getContext("2d");a=d.parent.fg_color.color.clone().inverse();d.cCanvas.clear(a);d.cCanvas.copy(d.parent.selected.cCanvas)})}Ctoolbox_preview.prototype=Object.create(Cobject.prototype);Ctoolbox_preview.prototype.constructor=new Cobject;
Ctoolbox_preview.prototype.init=function(){this.cCanvas=new Ccanvas({parent:this,width:100,height:100,src:"img/loading_toolbar_brush.png"})};Ctoolbox_preview.prototype.dom_build=function(){var a=$("<div />");a.addClass("toolbox-preview");var d=$("<div />");d.append(this.cCanvas.dom_get());a.append(d);this.rootElm=a;return this};function Ctoolbox_colorpicker(a,d){d.className="Ctoolbox_colorpicker";Cobject.call(this,d,["parent","label","callback_onchange"]);if(a&&!(a instanceof Ccolor))return console.error("color parameter is not an instance of Ccolor"),null;this.color=a?a:new Ccolor;this.rootElm=null;this.cCanvas=new Ccanvas({width:32,height:32});this.ctx=this.cCanvas.getContext();this.clear(this.color)}Ctoolbox_colorpicker.prototype=Object.create(Cobject.prototype);Ctoolbox_colorpicker.prototype.constructor=new Cobject;
Ctoolbox_colorpicker.prototype.clear=function(a){this.cCanvas.clear(a)};Ctoolbox_colorpicker.prototype.to_rgba=function(){return this.color.to_rgba()};
Ctoolbox_colorpicker.prototype.dom_build=function(){var a=this;if(this.rootElm)return this;var d=document.createElement("div"),d=$(d),e=document.createElement("canvas");e.setAttribute("width",32);e.setAttribute("height",32);e.setAttribute("alt",this.label);e.setAttribute("title",this.label);this.elmImage=e;d.append(e);var f=e.getContext("2d"),h=this.cCanvas.data;f.drawImage(h,0,0,h.width,h.height);var i=function(d){a.color.set_rgb(d);a.clear(a.color);f.drawImage(h,0,0,h.width,h.height);var e;(e=a.callback_exists("onchange"))&&
e.call(a,d)};$(e).ColorPicker({onChange:function(a,d,e){i.call(this,e)},onSubmit:function(a,d,e){i.call(this,e)},zIndex:10});this.rootElm=d;return this};function Ctoolbox(a,d){var e=this;this.olist=a;d.className="Ctoolbox";d.label="toolbox";Cobject.call(this,d,["parent"]);this.elmOptions=this.elmPreview=null;this.bind_trigger(this,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);e.update()})}Ctoolbox.prototype=Object.create(Cobject.prototype);Ctoolbox.prototype.constructor=new Cobject;
Ctoolbox.prototype.init=function(){var a=this;this.selected=null;this.tools=[];this.preview=new Ctoolbox_preview({parent:this});this.fg_color=new Ctoolbox_colorpicker(new Ccolor(255,255,255,1),{parent:this,callback_onchange:function(){a.send_trigger("update")},label:"Foreground color"});this.bg_color=new Ctoolbox_colorpicker(new Ccolor(0,0,0,1),{parent:this,callback_onchange:function(){a.send_trigger("update")},label:"Background color"});this.bind_trigger(this,"update",function(d){4<SHOJS_DEBUG&&
console.log("[Trigger/received]",d.type);a.selected&&a.selected.update()});this.load(this.olist);this.dom_build()};
Ctoolbox.prototype.load=function(a){var d=this,e=null,f=function(){d.send_trigger("update")};for(label in a)if("brush"in a[label]){a[label].parent=this;for(p in a[label].parameters)a[label].parameters[p].callback_change=f,a[label].parameters[p].callback_slide=f;var h=new Ctool(a[label]);h.update();this.tools.push(h);"pen"==label&&(console.log("selecting pen"),e=h)}else console.error("Tool need brush");this.selected=e;this.select_tool(this.selected)};
Ctoolbox.prototype.update=function(){if(!this.selected)return!1;this.selected.update()};Ctoolbox.prototype.select_tool=function(a){if(void 0==a)return console.warn("Can't select undefined tool"),!1;var d=$(a.rootElm);d.parent().children("div").removeClass("selected");d.addClass("selected");d=d.parents(".toolbox").find(".group-options");d.children("div").detach();d.append(a.dom_build_options());this.selected=a;a.update();this.send_trigger("update");return!0};
Ctoolbox.prototype.switch_color=function(){var a=this.fg_color;this.fg_color=this.bg_color;this.bg_color=a;a=this.rootElm.find(".colorpicker-colors");a.children(".colorpicker").detach();this.dom_build_colorpickers(a);this.send_trigger("update")};Ctoolbox.prototype.dom_build_colorpickers=function(a){a.append(this.fg_color.dom_get());a.append(this.bg_color.dom_get())};
Ctoolbox.prototype.dom_build=function(){var a=this,d=$('<div title="Toolbox"/>');d.addClass("toolbox");var e=$("<div />");e.addClass("group-tools ui-widget-content");for(var f=0;f<this.tools.length;f++)e.append(this.tools[f].dom_get());d.append(e);e=$("<div/>");e.addClass("ui-widget-content group-colorpicker");f=$("<div/>");f.addClass("ui-widget-content colorpicker-colors");this.dom_build_colorpickers(f);e.append(f);e.append($((new Cimage({src:"img/16x16_toggle_color.png",callback_onload:function(){},
callback_click:function(){a.switch_color()},label:"Switch color"})).dom_get().addClass("switch")));d.append(e);e=$("<div/>");e.addClass("group-preview ui-widget-content");e.append(this.preview.dom_get());d.append(e);e=$(document.createElement("div"));e.addClass("group-options ui-widget-content");d.append(e);this.rootElm=d;return this};var E_LAYERLABEL=Object({current:"_current",mouse:"_mouse",grid:"_gris",prefrag:"_prefrag"}),cRegistry;
function _ok_to_build(){cRegistry=new Cregistry;var a=new Csurface("surface-01",640,480);$(document).bind("shojs-cgrapher-grapher-error",function(a,d){console.log("bind",a,d);if("no-tool-selectionned"!=d)return!1;var e=$('<div class="dialog-error" title="Select tool first!">');e.append("<p>You must select a tool before drawing onto surface</p>");e.dialog({modal:!0,resizable:!1,buttons:{Ok:function(){$(this).dialog("close")}}})});var d=function(a,d){this.options=d;var e={autoOpen:!0,resizable:!0,draggable:!0,
width:250,zIndex:10,dialogClass:"shojs-dialog",stack:!0},j;for(j in e)j in d||(d[j]=e[j]);a.dialog(d);return a};$("#shojs-menu-top").menu({});d($(".shojs-menu-dialog"),{position:"right"});var e=d(a.cToolbox.dom_get(),{position:"left top"});d(a.layer_manager.dom_get(),{position:{my:"right top",at:"right bottom",of:e,collision:"fit"}});d(a.dom_get(),{width:a.width+100,position:"middle middle",stack:!1});e=d((new Cjquery_theme).dom_get(),{height:60,position:"right top"});e=d(a.cGrid.dom_get(),{position:{my:"right top",
at:"right bottom",of:e,collision:"fit"}});d(a.cMouse.dom_get(),{height:120,position:{my:"right top",at:"right bottom",of:e,collision:"fit"}});$("#button-save").click(function(){a.save_as_json()});$("#button-select-by-color").click(function(){a.cCanvas.select_by_color(new Ccolor(0,0,0,1))});$("#button-about").click(function(){var a=new Clicense;d(a.dom_get(),{width:600})});$(function(){$(this).bind("contextmenu",function(a){a.preventDefault()})});document.getElementById("shojs-open-file").addEventListener("change",
function(d){d=d.target.files;console.log("plop");for(var e=[],i=0,j;j=d[i];i++)e.push("<li><strong>",escape(j.name),"</strong> (",j.type||"n/a",") - ",j.size," bytes, last modified: ",j.lastModifiedDate?j.lastModifiedDate.toLocaleDateString():"n/a","</li>");document.getElementById("shojs-file-list").innerHTML="<ul>"+e.join("")+"</ul>";console.log(d);d=d[0];if(!d.type.match("image.*"))return console.log("Error: you can only load file"),!1;e=new FileReader;console.log("BOOM");e.onload=function(d){var e=
$("#candecoke");e.empty();var f=$("<canvas>");console.log("Loaded",d);var h=$("<img />");h[0].src=d.target.result;f.width=h.width;f.height=h.height;d=f[0].getContext("2d");console.log("Can de coke",f);width=h.width;height=h.height;d.drawImage(h[0],0,0,width,height);d.drawImage(h[0],0,0);a.layer_manager.selected.drawImage(f[0],0,0,width,height,0,0,width,height);e.append(f);e.append(h)};e.readAsDataURL(d)},!1)}
$(document).ready(function(){if(isCanvasSupported())_ok_to_build();else{var a=$(document.createElement("div"));a.attr("title","HTML5 error");a.addClass("error");a.append("<p>Your internet browser doesn't support <b>canvas</b> element.<br><b>canvas</b> is part of HTML 5 specification<br> Browser who must support it are Chrome, Firefox, Safari</p>");a.dialog({modal:!0,close:function(){console.log("close");$("body").empty();document.location="http://github.com/shojs/graphit"}})}});
