function Cimage_analyse(a){Cardinal={nw:7,n:0,ne:1,w:6,e:2,sw:5,s:4,se:3};a=a||{};a.className="Cimage_analyse";a.label="Cimage_analyse";Cobject.call(this,a,["source_points","image_data"])}Cimage_analyse.prototype=Object.create(Cobject.prototype);Cimage_analyse.prototype.constructor=new Cobject;
Cimage_analyse.prototype.get_cardinal_pixel=function(a,d,e){var f=d.x,d=d.y,h=a.width,i=h*a.height,j=[],a=function(a,d){var f=d*h+a;void 0==e[f]&&0<=f&&f<i&&j.push({x:a,y:d,index:f})};a(f,d-1);a(f+1,d-1);a(f+1,d);a(f+1,d+1);a(f,d+1);a(f-1,d+1);a(f-1,d);a(f-1,d-1);return j};Cimage_analyse.prototype.select_adjacent_pixel=function(a,d,e,f){a=this.get_cardinal_pixel(a,d,e);for(d=0;d<a.length;d++)f.call(this,a[d])};
Cimage_analyse.prototype.adjacent_by_color=function(a,d){for(var e=[],f=[],h=a.width*a.height,i=0;i<h;i++)e[i]=null;index=d.y*a.width+d.x;f.push({x:d.x,y:d.y,index:index});for(var j=0,h=0,k=(new Ccolor).from_pixel(a,d);0<f.length;)i=f.pop(),h++,this.select_adjacent_pixel(a,i,e,function(d){var h;h=(new Ccolor).from_pixel(a,d);h=k.equal(h,["r","g","b"])?!0:!1;h?(j++,e[d.index]=1,f.push(d)):e[d.index]=0});return e};var Eloading_status={none:1,loading:2,fail:3,ok:4};function Cimage(a){a=a||{};a.className="Cimage";a.label=a.label||"image";Cobject.call(this,a,"parent src width height title callback_click callback_success callback_error autoRelease".split(" "));this.options=a;this.data=null;this.status=Eloading_status.none;this.errorMsg="";this.last_update=null;this.src||console.warn(this.className+" constructed without src argument");this.dom_get()}Cimage.prototype=Object.create(Cobject.prototype);
Cimage.prototype.constructor=new Cobject;
Cimage.prototype.dom_build=function(){var a=this;if(this.rootElm&&!force)return console.warn("Image already loaded"),this;var d=$("<img />");d[0].onload=function(){return a.callback_onload.call(a)};d[0].onerror=function(){return a.callback_onerror.call(a)};d.click(function(){return a.callback_click.call(a)});"label"in this&&void 0!=this.label&&(d.attr("alt",this.label),d.attr("title",this.label));"width"in this&&void 0!=this.width&&d.attr("width",this.width);"height"in this&&void 0!=this.height&&
d.attr("height",this.height);"src"in this&&this.src&&d.attr("src",this.src);this.rootElm=d;return this};
Cimage.prototype.callback_onload=function(){this.status=Eloading_status.ok;this.last_update=Date.now();if("replace_id"in this.options&&this.options.replace_id){var a=document.getElementById(this.options.replace_id);a?("label"in this.options&&a.setAttribute("alt"),a.width=this.data.width,a.height=this.data.height,a.src=this.data.src):this.errorMsg="Replacing image failed"}return(a=this.callback_exists("success"))?a.call(this):!1};
Cimage.prototype.callback_onerror=function(){this.status=Eloading_status.fail;this.last_update=null;var a=this.callback_exists("error");return a?a.call(this):!1};Cimage.prototype.callback_click=function(){var a=this.callback_exists("click");return a?a.call(this):!1};function Cicon(a){a=a||{};a.className="Cicon";a.size=a.size||22;a.type=a.type||"gimp";a.format=a.format||"png";a.label=a.label||"icon";a.path=a.path?"/"+a.path+"/":"/";a.src=this._build_src_path(a);console.log("Loading icon",a.src);Cimage.call(this,a,["name","format","size","path"])}Cicon.prototype=Object.create(Cimage.prototype);Cicon.prototype.constructor=new Cimage;
Cicon.prototype._build_src_path=function(a){a.name||this.exception("mandatory_parameter_missing","name");return"images/"+a.type+a.path+a.name+"-"+a.size+"."+a.format};var Ecolor={transparent_black:"rgba(0,0,0,0)"};function Ccolor(a,d,e,f){this.className="Ccolor";this.r=a;this.g=d;this.b=e;this.a=f}Ccolor.prototype.to_rgba=function(){return"rgba("+this.r+","+this.g+","+this.b+","+this.a+")"};Ccolor.prototype.set_rgb=function(a){this.r=a.r;this.g=a.g;this.b=a.b;this.a=1;return this};Ccolor.prototype.set=function(a,d){if(a in this)return this[a]=d,this;console.error("Invalid key",a);return null};
Ccolor.prototype.from_rgba=function(a){var d=RegExp(/^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+(\.\d+)?)\s*\)$/).exec(a);if(!d)return console.error("Invalid rgba expression: "+a),this;this.r=d[1];this.g=d[2];this.b=d[3];this.a=d[4];return this};Ccolor.prototype.inverse=function(){var a=1/255;this.r=Math.round(255*(1-this.r*a));this.g=Math.round(255*(1-this.g*a));this.b=Math.round(255*(1-this.b*a));return this};
Ccolor.prototype.from_pixel=function(a,d){if(void 0==a||void 0==d)throw"invalid_argument";var e=d.y*4*a.width+4*d.x,f=a.data;this.r=f[e];this.g=f[e+1];this.b=f[e+2];this.a=f[e+3];this.a=Math.round(100*(this.a/255))/100;return this};Ccolor.prototype.clone=function(){return new Ccolor(this.r,this.g,this.b,this.a)};Ccolor.prototype.equal=function(a,d){for(var e=d||["a","r","g","b"],f,h=0;h<e.length;h++)if(f=e[h],this[f]!=a[f])return!1;return!0};
Ccolor.prototype.magnitude=function(){return Math.sqrt(this.r*this.r+this.g*this.g+this.b*this.b)};Ccolor.prototype.normalize=function(){var a=this.magnitude();this.r/=a;this.b/=b;this.g/=g;return this};Ccolor.prototype.to_s=function(){return this.className+"("+this.r+", "+this.g+", "+this.b+", "+this.a+")\n"};function Cmenu(a){a=a||{};a.className="Cmenu";a.label=a.label||"menu";a.type=a.type||"jquery";this.entries={};this.num_child=0;Cobject.call(this,a,["type","parent"])}Cmenu.prototype=Object.create(Cobject.prototype);Cmenu.prototype.constructor=new Cobject;Cmenu.prototype.init=function(a){for(var d in a.entries)a.entries[d].parent=this,a.entries[d].type=this.type,this.add(new Cmenu(a.entries[d]))};Cmenu.prototype.exists=function(a){return a.label in this.entries?!0:!1};
Cmenu.prototype.add=function(a){(!a||!(a instanceof Cmenu))&&this.exception("invalid_menu_entry",a);this.exists(a)&&this.exception("label_already_present",a.label);this.entries[a.label]=a;this.num_child++};
Cmenu.prototype.dom_build=function(){var a;a=parent in this&&this.parent instanceof Cmenu?this.parent.rootElm:$("<ul />");for(var d in this.entries){var e=this.entries[d],f=$('<a href="#" title=""/>');f.attr("label",d);"click"in e.callback&&e.install_callback(f);var h=$("<li />"),i=$("<span>"+d+"</span>");f.append(i);h.append(f);e.has_child()&&(e=e.dom_get({noHeader:!0}),h.append(e));a.append(h)}if("jquery"==this.type&&(!this.parent||!(this.parent instanceof Cmenu)))a.menu({role:"listbox"}),a.menu("enable");
if(!this.parent||!(this.parent instanceof Cmenu))d=$("<div />"),d.append(a),a=d;this.rootElm=a;return this};Cmenu.prototype.has_child=function(){return 0<this.num_child?!0:!1};Cmenu.prototype.install_callback=function(a){var d=this;a.click(function(){d.callback.click()})};Cmenu.prototype.count_childs=function(){var a=0;for(c in this.entries)a++;return a};function Ccanvas(a){a=a||{};a.className="Ccanvas";a.label="canvas";Cobject.call(this,a,["width","height","bg_color","src"]);this.bg_color=this.bg_color||new Ccolor(0,0,0,0);(!this.width||0>this.width||1920<this.width)&&this.exception("invalid_width",this.width);(!this.height||0>this.height||1280<this.height)&&this.exception("invalid_height",this.height);this.data=document.createElement("canvas");this.data.setAttribute("width",this.width);this.data.setAttribute("height",this.height);this.ctx=this.data.getContext("2d");
this.clear(this.bg_color);this.src&&this.load(this.src)}Ccanvas.prototype=Object.create(Cobject.prototype);Ccanvas.prototype.constructor=new Cobject;Ccanvas.prototype.clone=function(){var a=new Ccanvas({width:this.width,height:this.height,bg_color:this.bg_color});a.copy({src:this});return a};Ccanvas.prototype.get_width=function(){return this.data.width};Ccanvas.prototype.get_height=function(){return this.data.height};
Ccanvas.prototype.getImageData=function(a,d,e,f){return this.data.getContext("2d").getImageData(a,d,e,f)};
Ccanvas.prototype.copy=function(a){!a.src&&(!(a.src instanceof Ccanvas)||!(a.src instanceof Cimage))&&this.exception("invalid_copy_source");var d=null,e,f,h,i=null;e=this.get_width();f=this.get_height();a.src instanceof Ccanvas?(d=a.src.data,h=a.src.get_width(),i=a.src.get_height()):(d=a.src,h=d.width,i=d.height,console.log("sw, dw",h,i));a.resize=void 0!=a.resize?a.resize:!1;var j=this.data.getContext("2d");j.save();"undefined"!=a.resize&&a.resize?j.drawImage(d,0,0,h,i,0,0,e,f):a.keepRatio?(d=this.data.width,
f=a.src.get_width()/a.src.get_height()/d,f*=this.data.height,j.drawImage(a.src.data,0,0,a.src.get_width(),a.src.get_height(),0,0,d,f)):(a=h>e?e:h,i=i>f?f:i,e=e>a?(e-a)/2:0,f=f>i?(f-i)/2:0,e=f=0,j.drawImage(d,0,0,a,i,e,f,a,i));j.restore()};Ccanvas.prototype.get_pixel_color=function(a,d,e,f){return a.data[d*4*a.width+4*e+f]};Ccanvas.prototype.getCanvas=function(){return this.data};
Cobject.prototype.getContext=function(a){a=a||"2d";if("data"in this)return this.data.getContext(a);console.error("Cannot return context for this object... no cCanvas");return null};Ccanvas.prototype.clear=function(a){var a=a||new Ccolor(0,0,0,0),d=this.getContext();0==a.a?d.clearRect(0,0,this.data.width,this.data.height):(d.save(),d.fillStyle=a.to_rgba(),d.fillRect(0,0,this.data.width,this.data.height),d.restore())};
Ccanvas.prototype.save=function(){var a=this.data.toDataURL("image/png");window.open(a)||(document.location.href=a)};var Ergb_color={red:0,green:1,blue:2,alpha:3};
Ccanvas.prototype.select_by_color=function(a){console.log("Selecting by color",a);var d=this.ctx.getImageData(0,0,this.data.width,this.data.height);this.ctx.save();this.ctx.beginPath();var e=0,f=d.width,h=d.height,i=document.createElement("canvas");i.width=f;i.height=h;var j=i.getContext("2d");j.fillStyle="rgba(0,0,0,1)";j.clearRect(0,0,f,h);j.translate(-0.5,-0.5);for(var k=0;k<h;k+=1)for(var l=0;l<f;l+=1)Math.round(100*(this.get_pixel_color(d,k,l,Ergb_color.alpha)/255))/100==a.a&&(this.get_pixel_color(d,
k,l,Ergb_color.red)==a.r&&this.get_pixel_color(d,k,l,Ergb_color.green)==a.g&&this.get_pixel_color(d,k,l,Ergb_color.blue)==a.b)&&(j.save(),j.translate(l,k),j.fillRect(0,0,1,1),j.restore(),e++);console.log("total line",e,[]);new Ccanvas(f,h,new Ccolor(0,0,0,1));this.ctx.clearRect(0,0,f,h);this.ctx.drawImage(i,0,0,f,h);this.ctx.restore()};
Ccanvas.prototype.to_bitmask=function(a){console.log(a);var d,e,f,h;a?(d=a,f=a.getContext("2d"),e=f.getImageData(0,0,a.width,a.height),h=a.width,a=a.height):(d=this.data,f=this.ctx,e=this.ctx.getImageData(0,0,this.data.width,this.data.height),h=this.data.width,a=this.data.heignt);var i=null;f.save();f.fillStyle="rgba(0,1,1,1)";f.clearRect(0,0,h,a);f.translate(-0.5,-0.5);for(var j=0;j<a;j+=1)for(var k=0;k<h;k+=1)i=this.get_pixel_color(e,j,k,Ergb_color.alpha)/255,f.save(),f.translate(k,j),1==i?f.clearRect(0,
0,1,1):f.fillRect(0,0,1,1),f.restore();f.restore();this.ctx.clearRect(0,0,this.data.width,this.data.height);this.ctx.drawImage(d,0,0,h,a)};
Ccanvas.prototype.load=function(a){var d=this;this.image_loading=new Cimage({src:a,callback_onload:function(){console.log("Image loaded",this);var a=cMath.clamp(1,this.rootElm.width,d.data.width),f=cMath.clamp(1,this.rootElm.height,d.data.height);d.data.getContext("2d").drawImage(this.rootElm,0,0,a,f);d.image_loading=null},callback_onerror:function(){console.log("Failed to load image",this);d.image_loading=null}})};Ccanvas.prototype.dom_build=function(){this.rootElm=this.data;return this};function Cregistry(){this.store=null;this.localStorage=new Clocal_storage;this.store=this.localStorage.store?this.localStorage.store:[]}Cregistry.prototype.set=function(a,d){this.store[a]=d;return this};Cregistry.prototype.get=function(a){return this.store[a]};Cregistry.prototype.get_set=function(a,d){var e;this.store[a+"_default"]=d;return(e=this.get(a))?e:this.store[a]=d};function Cpo(a){PO={en:{menu_new_surface:"New",menu_theme:"Theme",menu_about:"About",menu_toolbox:"Toolbox",menu_file:"File",menu_help:"Help",menu_edition:"Edition",foreground_color:"Foreground color",background_color:"Background color",layers:"Layers",switch_color:"Switch color",tool_pencil:"Pen",tool_paintbrush:"Brush",tool_eraser:"Eraser","tool_bucket-fill":"Fill",right_click_to_save:"Right click -> Save as",save_image:"Save image",save:"Save",open:"Open",load:"Load",load_image:"Load image (URL)"},
fr:{menu_new_surface:"Nouveau",menu_theme:"Theme",menu_about:"A propos",menu_file:"Fichier",menu_help:"Aide",menu_edition:"Edition",menu_toolbox:"Outils",foreground_color:"Couleur principal",background_color:"Couleur de fond",layers:"Calques",switch_color:"Echange de couleur",tool_pencil:"Crayon",tool_paintbrush:"Pinceau",tool_eraser:"Gomme",tool_bucket_fill:"Remplir",right_click_to_save:"Clique droit -> Enregistrer l'image sous",save:"Sauver",open:"Ouvrir",load:"Charger",load_image:"Charger image (URL)"}};
a=a||{};a.className="Cpo";a.label="po";a.def="en";Cobject.call(this,a,["lang","def"])}Cpo.prototype=Object.create(Cobject.prototype);Cpo.prototype.constructor=new Cobject;Cpo.prototype.get=function(a){var d="";if(this.lang in PO&&a in PO[this.lang])d=PO[this.lang][a];else if(this.def in PO&&a in PO[this.def])d=PO[this.def][a];else throw new Cexception_message({className:this.className,label:"no_trad_and_no_def",object:"",additional:a});return d};var cMath={distance:function(a,d){var e=d.x-a.x,f=d.y-a.y;return Math.sqrt(e*e)+f*f},isint:function(a){return"number"===typeof a&&0==a%1},linear_interpolation:function(a,d,e){var e=1,f=[],h=new Cvector2d;h.from_point(a,d);var i=h.magnitude();if(0==i)return f;h.normalize();var j=a.clone();h.smul(e);f.push(a);for(a=0;a<=i;a+=e)j.vadd(h),f.push(new Cpoint2d(j));f.push(d);return f},clamp:function(a,d,e){return a<d?d:a>e?e:a}};function Cpoint2d(a){if(void 0!=a&&(!("x"in a)||!("y"in a)))throw new Cexception_message({className:"Cpoint",error:"invalid_component",additional:a});a=a||{x:0,y:0};Object.defineProperty(this,"x",{value:a.x,writable:!0,enumerable:!0,configurable:!1});Object.defineProperty(this,"y",{value:a.y,writable:!0,enumerable:!0,configurable:!1})}Cpoint2d.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y)};function Cvector2d(a){Cpoint2d.call(this,a)}Cvector2d.prototype=Object.create(Cpoint2d.prototype);Cvector2d.prototype.constructor=new Cpoint2d;Cvector2d.prototype.magnitude=function(){return 0==this.x&&0==this.y?0:Math.sqrt(this.x*this.x+this.y*this.y)};Cvector2d.prototype.normalize=function(){var a=this.magnitude();if(0==a)return this;this.x/=a;this.y/=a;return this};Cvector2d.prototype.from_point=function(a,d){this.x=d.x-a.x;this.y=d.y-a.y;return this};
Cvector2d.prototype.smul=function(a){this.x*=a;this.y*=a;return this};Cvector2d.prototype.vadd=function(a){this.x+=a.x;this.y+=a.y;return this};Cvector2d.prototype.clone=function(){return new Cvector2d(this)};function Cmatrix33(a){m11=0;m12=1;m13=2;m21=3;m22=4;m23=5;m31=6;m32=7;m33=8;this.data=[];a=void 0!=a?a:[1,0,0,0,1,0,0,0,1];this.set(a)}Cmatrix33.prototype.init=function(){};Cmatrix33.prototype.clone=function(){return new Cmatrix33(this)};Cmatrix33.prototype._is_valid_array=function(a){return 9==a.length?!0:!1};Cmatrix33.prototype.translate=function(a){a=new Cmatrix33([1,0,0,0,1,0,a.x,a.y,1]);this.mul(a);return this};
Cmatrix33.prototype.scale=function(a){a=new Cmatrix33([a.x,0,0,0,a.y,0,0,0,1]);this.mul(a);return this};Cmatrix33.prototype.rotate=function(a){var d=Math.cos(a),a=Math.sin(a),d=new Cmatrix33([d,a,0,-a,d,0,0,0,1]);this.mul(d);return this};
Cmatrix33.prototype.set=function(a){console.log(a);if(void 0==a)return this;if(a instanceof Array){if(!this._is_valid_array(a))throw"matrix33_invalid_array";for(var d=0;d<=m33;d++)this.data[d]=a[d]}else if(a instanceof Cmatrix33)for(d=0;d<=m33;d++)this.data[d]=a.data[d];else if("number"==typeof a){a=parseFloat(a);for(d=0;d<=m33;d++)this.data[d]=a}else throw"matrix33_invalid_value";return this};
Cmatrix33.prototype.add=function(a){if(!a)return this;if(a instanceof Array){if(!this._is_valid_array(a))throw"matrix33_invalid_array";for(var d=0;d<=m33;d++)this.data[d]+=a[d]}else if(a instanceof Cmatrix33)for(d=0;d<=m33;d++)this.data[d]+=a.data[d];else if("number"==typeof a){a=parseFloat(a);for(d=0;d<=m33;d++)this.data[d]+=a}else throw"matrix33_invalid_value";return this};Cmatrix33.prototype.round=function(){for(var a=0;a<=m33;a++)this.data[a]=Math.round(this.data[a]);return this};
Cmatrix33.prototype.floor=function(){for(var a=0;a<=m33;a++)this.data[a]=Math.floor(this.data[a]);return this};Cmatrix33.prototype.random=function(a){for(var a=a||1,d=0;d<=m33;d++)this.data[d]=Math.random(a);return this};Cmatrix33.prototype.identity=function(){this.data=[1,0,0,0,1,0,0,0,1];return this};
Cmatrix33.prototype.mul=function(a){console.log(a);if(!a)return this;if(a instanceof Cmatrix33||a instanceof Array&&9==a.length){var d=this.data,e=[],f=null,f=a instanceof Cmatrix33?a.data:a;console.log(d,f);e[m11]=d[m11]*f[m11]+d[m12]*f[m21]+d[m13]*f[m31];e[m12]=d[m11]*f[m12]+d[m12]*f[m22]+d[m13]*f[m32];e[m13]=d[m11]*f[m13]+d[m12]*f[m23]+d[m13]*f[m33];e[m21]=d[m21]*f[m11]+d[m22]*f[m21]+d[m23]*f[m31];e[m22]=d[m21]*f[m12]+d[m22]*f[m22]+d[m23]*f[m32];e[m23]=d[m21]*f[m13]+d[m22]*f[m23]+d[m23]*f[m33];
e[m31]=d[m31]*f[m11]+d[m32]*f[m21]+d[m33]*f[m31];e[m32]=d[m31]*f[m12]+d[m32]*f[m22]+d[m33]*f[m32];e[m33]=d[m31]*f[m13]+d[m32]*f[m23]+d[m33]*f[m33];console.log("m",e);this.data=e}else if("number"==typeof a){console.log(typeof a);a=parseFloat(a);for(d=0;d<=m33;d++)this.data[d]*=a}else throw"matrix33_invalid_value";return this};
Cmatrix33.prototype.minor=function(){var a=[],d=this.data;a[m11]=d[m22]*d[m33]-d[m32]*d[m23];a[m12]=d[m21]*d[m33]-d[m31]*d[m23];a[m13]=d[m21]*d[m32]-d[m31]*d[m22];a[m21]=d[m12]*d[m33]-d[m32]*d[m13];a[m22]=d[m11]*d[m33]-d[m31]*d[m13];a[m23]=d[m11]*d[m32]-d[m31]*d[m12];a[m31]=d[m12]*d[m23]-d[m22]*d[m13];a[m32]=d[m11]*d[m23]-d[m21]*d[m13];a[m33]=d[m11]*d[m22]-d[m21]*d[m12];this.data=a;return this};
Cmatrix33.prototype.to_s=function(a){var d="\n";a&&("format"in a&&"html"==a.format)&&(d="<br>\n");for(var a="Cmatrix33"+d+" ",e=0;e<=m33;e++)a+=this.data[e]+",",0==(e+1)%3&&(a+=d+" ");return a};function Ctransform2d(a){a=a||{};a.className="Ctransform2d";a.label="Ctransform2d";Cobject.call(this,a,[]);this.matrix=new Cmatrix33;this.matrix.identity();this.position=new Cvector2d;this.u=new Cvector2d;this.v=new Cvector2d}Ctransform2d.prototype=Object.create(Cobject.prototype);Ctransform2d.prototype.constructor=new Cobject;Ctransform2d.prototype.translate=function(a){(!("x"in a)||!1 in a)&&this.exception("camel_camouflage_failed");this.matrix.translate(a)};
Ctransform2d.prototype.rotate=function(a){(!("x"in a)||!1 in a)&&this.exception("camel_camouflage_failed");this.matrix.translate(a)};Ctransform2d.prototype.translate=function(a){a||this.exception("camel_camouflage_failed");this.matrix.translate(point)};function Cminmax(a,d){this.min=a;this.max=d;this.last=null}Cminmax.prototype.init=function(a){this.min=this.max=this.last=a};Cminmax.prototype.cmp=function(a){if(void 0==a)return console.warn("MinMax: Comparing with null value"),!1;a<this.min&&(this.min=a);a>max&&(this.max=a);this.last=a;return!0};function Cmouse_tracker_point(a){Cvector2d.call(this,a);this.time=Date.now()}Cmouse_tracker_point.prototype=Object.create(Cvector2d.prototype);
Cmouse_tracker_point.prototype.constructor=new Cvector2d({x:0,y:0});
function Cmouse_tracker(a){a.className="Cmouse_tracker";a.label="mousetracker";Cobject.call(this,a,["parent","callback_move","callback_track"]);this.y=this.x=0;this.cMinmaxX=new Cminmax(0,this.parent.width);this.cMinmaxY=new Cminmax(0,this.parent.height);this.minmax=Object({minx:0,maxx:this.parent.width,miny:0,maxy:this.parent.height});this.minx=this.minmax.maxx;this.maxx=0;this.miny=this.minmax.maxy;this.maxy=0;this.pushed=null;this.paused=!1;this.interval=null;this.points=[];this.rootElm=null;return this}
Cmouse_tracker.prototype=Object.create(Cobject.prototype);Cmouse_tracker.prototype.constructor=new Cobject;Cmouse_tracker.prototype.reset=function(){this.minx=this.minmax.maxx;this.maxx=0;this.miny=this.minmax.maxy;this.maxy=0;this.points=[]};Cmouse_tracker.prototype.move=function(a,d){a=cMath.clamp(Math.round(a),this.minmax.minx,this.minmax.maxx);d=cMath.clamp(Math.round(d),this.minmax.miny,this.minmax.maxy);this.x=a;this.y=d;var e=this.callback_exists("track");e&&e.call(this,a,d);return this};
Cmouse_tracker.prototype.push=function(){this.pushed=Date.now();var a=this;this.interval=setInterval(function(){if(!a.is_pushed())return clearInterval(a.interval),null;if(this.paused)return null;var d=new Cmouse_tracker_point(a);a.points.push(d);a.minx=Math.min(a.minx,d.x);a.maxx=Math.max(a.maxx,d.x);a.miny=Math.min(a.miny,d.y);a.maxy=Math.max(a.maxy,d.y)},1E3/120);this.func_push&&this.func_push(this)};
Cmouse_tracker.prototype.dom_build=function(){var a=$("<div />");a.attr("title","Mouse tracker");a.addClass("mousetracker");var d=document.createElement("div"),d=$(d);d.addClass("ui-widget-content");d.append('<div class="hold-var"><h6>x:&nbsp;</h6><span class="var-x">'+this.x+"</span></div>");d.append('<div class="hold-var"><h6>y:&nbsp;</h6><span class="var-y">'+this.y+"</span></div>");a.append(d);this.rootElm=a;return this};
Cmouse_tracker.prototype.release=function(){this.pushed=null;this.func_release&&this.func_release(this);this.reset()};Cmouse_tracker.prototype.is_pushed=function(){return this.pushed};Cmouse_tracker.prototype.to_s=function(){return"Cmouse_tracker: "+this.x+" / "+this.y};function Cwidget(a,d){Cobject.call(this);this.label=d;this.parent=a;this.dom=null}Cwidget.prototype=Object.create(Cobject.prototype);Cwidget.prototype.constructor=new Cobject;Cwidget.prototypeedom_get=function(a){return this.dom&&!a?this.dom:this.dom_build().dom};function Cwidget_window_header(a,d){Cwidget.call(this,a,d)}Cwidget_window_header.prototype=Object.create(Cwidget.prototype);Cwidget_window_header.prototype.constructor=new Cwidget;
Cwidget_window_header.prototype.dom_build=function(){var a=$(document.createElement("div"));a.addClass("window-header");a.append(this.label);this.dom=a;return this};function Cwidget_window(a,d){Cwidget.call(this,a,d);this.wHeader=new Cwidget_window_header(this,d)}Cwidget_window.prototype=Object.create(Cwidget.prototype);Cwidget_window.prototype.constructor=new Cwidget;
Cwidget_window.prototype.dom_build=function(){var a=$(document.createElement("div"));a.addClass("widget-window");a.append(this.wHeader.dom_get());this.dom=a;return this};var WM=new Cwidget_window;var CTOOL_brushes={circle:{width:100,height:100,callback_update:function(){var a=this.parent.parent;if(!(a instanceof Ctoolbox))return console.error("Brush parent of parent must be a toolbox"),!1;var d=a.fg_color.color.clone(),a=a.selected;"opacity"in a.parameters&&(d.a=a.parameters.opacity.value);a=this.cCanvas.data.width/2;this.cCursor=new Ccanvas({width:this.cCanvas.width,height:this.cCanvas.height});cDraw.circle({dcanvas:this.cCursor.data,x:a,y:a,r:a,fillStyle:new Ccolor(255,0,0,0.4),strokeStyle:new Ccolor(255,
0,0,1),lineWidth:1});cDraw.circle({dcanvas:this.cCanvas.data,x:a,y:a,r:a,fillStyle:d})}},scircle:{width:100,height:100,callback_update:function(){var a=this.parent.parent;if(!(a instanceof Ctoolbox))return console.error("Brush parent of parent must be a toolbox"),!1;var d=a.fg_color.color.clone();if((a=a.selected)&&"opacity"in a.parameters)d.a=a.parameters.opacity.value;a=this.cCanvas.data.width/2;this.cCursor=new Ccanvas({width:this.cCanvas.width,height:this.cCanvas.height});cDraw.circle({dcanvas:this.cCursor.data,
x:a,y:a,r:a,fillStyle:new Ccolor(255,0,0,0.4),strokeStyle:new Ccolor(255,0,0,1),lineWidth:1});cDraw.circle({dcanvas:this.cCanvas.data,x:a,y:a,r:a,strokeStyle:d})}},rectangle:{width:100,height:100,callback_update:function(){var a=this.parent.parent;if(!(a instanceof Ctoolbox))return console.error("Brush parent of parent must be a toolbox"),!1;var d=a.fg_color.color.clone();if((a=a.selected)&&"opacity"in a.parameters)d.a=a.parameters.opacity.value;a=this.cCanvas.data.width;this.cCursor=new Ccanvas({width:this.cCanvas.width,
height:this.cCanvas.height});var e=this.cCursor.getContext();e.save();e.clearRect(0,0,a,a);e.strokeStyle=d.to_rgba();e.strokeRect(0,0,a,a);e.restore();e=this.cCanvas.getContext();e.save();e.clearRect(0,0,a,a);e.fillStyle=d.to_rgba();e.fillRect(0,0,a,a);e.restore()}}},Ecomposite_operation={"source-over":"source-over","source-in":"source-in","source-out":"source-out","source-atop":"source-atop",lighter:"lighter",xor:"xor","destination-over":"destination-over","destination-in":"destination-in","destination-out":"destination-out",
"destination-atop":"destination-atop",darker:"darker"},CTOOL_tools={pencil:{label:"pencil",parameters:{size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},linecap:{type:Eparameter_type.select,label:"linecap",choices:{round:"round",butt:"butt",square:"square"},def:"round"}},brush:CTOOL_brushes.circle,_graph:function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");d.save();d.lineWidth=Math.round(this.parameters.size.value);
var e=a.fgColor.color.clone();e.a=this.parameters.opacity.value;d.strokeStyle=e.to_rgba();d.lineCap=this.parameters.linecap.value;d.beginPath();d.moveTo(a.A.x,a.A.y);d.lineTo(a.B.x,a.B.y);d.stroke();d.closePath();d.restore();return!0}},paintbrush:{label:"paintbrush",parameters:{size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},pression:{label:"pression",min:0.1,max:100,def:100,step:0.01}},brush:CTOOL_brushes.circle,_update:function(){return!0},_graph:function(a){var d=
a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),e=this.cCanvas.data,f=e.width/2,h=e.height/2;e.getContext("2d");var i=this.get_parameter("pression"),a=cMath.linear_interpolation(a.A,a.B,100/i);if(0>=a.length)return!1;for(i=0;i<a.length;i++)d.save(),a[i].round(),d.translate(a[i].x-f,a[i].y-h),d.drawImage(e,0,0,e.width,e.height),d.restore();return!0}},eraser:{label:"eraser",parameters:{size:{label:"size",min:1,max:100,def:20,step:1},pression:{label:"pression",min:0.1,max:100,
def:100,step:0.01}},compositeOperation:Ecomposite_operation.xor,brush:CTOOL_brushes.circle,_update:function(){},_pregraph:function(){var a=this.parent.parent.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),d=this.parent.parent.layer_manager,e;d.special_layers.stack_down&&(e=d.special_layers.stack_down.cCanvas.data,a.drawImage(e,0,0,e.width,e.height));e=d.selected.cCanvas.data;a.drawImage(e,0,0,e.width,e.height)},_graph:function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");
a.cSurface.layer_manager.special_layers.prefrag.down_composite_operation=Ecomposite_operation["source-in"];d.globalCompositeOperation=Ecomposite_operation["destination-out"];for(var e=this.cCanvas.data,f=e.width/2,h=e.height/2,i=this.get_parameter("pression")||100,a=cMath.linear_interpolation(a.A,a.B,100/i),i=0;i<a.length;i++)d.save(),d.translate(a[i].x-f,a[i].y-h),d.drawImage(e,0,0,e.width,e.height),d.restore();d.restore();return!0},_postgraph:function(a,d,e,f){var h=this.parent.parent.selected.layer_manager.selected,
i=this.parent.parent.selected.layer_manager.special_layers.prefrag,j=i.clone(),k=j.cCanvas.getContext("2d");k.save();k.clearRect(0,0,j.cCanvas.data.width,j.cCanvas.data.height);k.globalCompositeOption="xor";k.drawImage(i.cCanvas.data,0,0,i.cCanvas.data.width,i.cCanvas.data.height);h.drawImage(j.cCanvas.data,a,d,e,f,0,0,"source-in");k.restore()}}};function Ctool(a){var d=this,a=a||{};a.className="Ctool";a.label=a.label||"tool";this.cCanvas=this.brush=null;this.need_update=!0;this.optElm=this.rootElm=null;this.changeCursor=!0;for(e in a.parameters)a.parameters[e].parent=this;Cobject.call(this,a,"parent brush label _pregraph _graph _postgraph _update compositeOperation".split(" "));for(var e in this.parameters)this.bind_trigger(this.parameters[e],"update",function(){d.update()});return this}Ctool.prototype=Object.create(Cobject.prototype);
Ctool.prototype.constructor=new Cobject;Ctool.prototype.canvas_create=function(a,d){if(!a||0>a||1920<a)return console.error("Width not in range",a),null;if(!d||0>d||1080<d)return console.error("Height not in range",d),null;this.set_parameter("width",a);this.set_parameter("height",d)};Ctool.prototype.set_options=function(a){if(!a.brush)return console.error("No brush in Ctool options"),!1};
Ctool.prototype.update=function(){this.need_update=!0;if(!this.need_update)return console.log("Doesn't need update"),!1;var a=this.get_parameter("size");a||this.exception("no_size_parameter",this.label);this.cCanvas=new Ccanvas({width:a,height:a});this.ctx=this.cCanvas.getContext("2d");a=this.parent.brush_manager.selected.cCanvas.data;this.ctx.drawImage(a,0,0,a.width,a.height,0,0,this.cCanvas.get_width(),this.cCanvas.get_height());this.need_update=!1;this.send_trigger("update")};
Ctool.prototype.drawImage=function(a,d,e){var f=a.getContext("2d"),h=this.cCanvas.canvas;if(!f)return console.error("Cannot acquire context"),!1;if(d>a.width||0>d)return console.error("x not in canvas destination range",d),!1;if(e>a.height||0>e)return console.error("y not in canvas destination range",e),!1;f.drawImage(h,0,0,h.width,h.height,d,e,h.width,h.height);return!0};Ctool.prototype.onclick=function(){"callback_onclick"in this.options&&"function"===typeof this.options.callback_onclick&&this.options.callback_onclick(this)};
Ctool.prototype.dom_build=function(a){if(this.rootElm&&!a)return this;a=$("<div />");a.append(this.dom_build_tool());this.rootElm=a;return this};Ctool.prototype.dom_build_tool=function(){var a=this,d=new Cicon({path:"tools",name:"stock-tool-"+this.label,callback_click:function(){a.send_trigger("tool_selected",a)},label:T("tool_"+this.label)});return $(d.dom_get().addClass("group tool"))};
Ctool.prototype.dom_build_options=function(){if(this.optElm)return this.optElm;var a=$(document.createElement("div"));a.addClass("not-draggable");for(label in this.parameters)a.append(this.parameters[label].dom_get());return this.optElm=a};Ctool.prototype.callback_click=function(){this.parent&&this.parent.select_tool(this)};Ctool.prototype.graph=function(){this.exceptions("method_must_be_overidden")};Ctool.prototype.pre_graph=function(){};Ctool.prototype.post_graph=function(){};function Ctool_pencil(a){a=a||{};a.className="Ctool_pencil";a.label="pencil";a.parameters={size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},linecap:{type:Eparameter_type.select,label:"linecap",choices:{round:"round",butt:"butt",square:"square"},def:"round"}};Ctool.call(this,a,[])}Ctool_pencil.prototype=Object.create(Ctool.prototype);Ctool_pencil.prototype.constructor=new Ctool;
Ctool_pencil.prototype.graph=function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");d.save();d.lineWidth=Math.round(this.parameters.size.value);var e=a.fgColor.color.clone();e.a=this.parameters.opacity.value;d.strokeStyle=e.to_rgba();d.lineCap=this.parameters.linecap.value;d.beginPath();d.moveTo(a.A.x,a.A.y);d.lineTo(a.B.x,a.B.y);d.stroke();d.closePath();d.restore();return!0};function Ctool_paintbrush(a){a=a||{};a.className="Ctool_paintbrush";a.label="paintbrush";a.parameters={size:{label:"size",min:1,max:100,def:20,step:1},opacity:{label:"opacity",min:0,max:1,def:1,step:0.01},pression:{label:"pression",min:0.1,max:100,def:100,step:0.01}};Ctool.call(this,a,[])}Ctool_paintbrush.prototype=Object.create(Ctool.prototype);Ctool_paintbrush.prototype.constructor=new Ctool;
Ctool_paintbrush.prototype.graph=function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),e=this.cCanvas.data,f=e.width/2,h=e.height/2,i=this.get_parameter("pression"),a=cMath.linear_interpolation(a.A,a.B,100/i);if(0>=a.length)return!1;for(i=0;i<a.length;i++)d.save(),a[i].round(),d.translate(a[i].x-f,a[i].y-h),d.drawImage(e,0,0,e.width,e.height),d.restore();return!0};function Ctool_eraser(a){a=a||{};a.className="Ctool_eraser";a.label="eraser";a.compositeOperation=Ecomposite_operation.xor;a.parameters={size:{label:"size",min:1,max:100,def:20,step:1},pression:{label:"pression",min:0.1,max:100,def:100,step:0.01}};Ctool.call(this,a,[])}Ctool_eraser.prototype=Object.create(Ctool.prototype);Ctool_eraser.prototype.constructor=new Ctool;
Ctool_eraser.prototype.pre_graph=function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),a=a.cSurface.layer_manager,e;a.special_layers.stack_down&&(e=a.special_layers.stack_down.cCanvas.data,d.drawImage(e,0,0,e.width,e.height));e=a.selected.cCanvas.data;d.drawImage(e,0,0,e.width,e.height)};
Ctool_eraser.prototype.post_graph=function(a,d,e,f,h){var i=a.cSurface.layer_manager.selected,a=a.cSurface.layer_manager.special_layers.prefrag,j=a.clone(),k=j.cCanvas.getContext("2d");k.save();k.clearRect(0,0,j.cCanvas.data.width,j.cCanvas.data.height);k.globalCompositeOption="xor";k.drawImage(a.cCanvas.data,0,0,a.cCanvas.data.width,a.cCanvas.data.height);i.drawImage(j.cCanvas.data,d,e,f,h,0,0,"source-in");k.restore()};
Ctool_eraser.prototype.graph=function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d");a.cSurface.layer_manager.special_layers.prefrag.down_composite_operation=Ecomposite_operation["source-in"];d.globalCompositeOperation=Ecomposite_operation["destination-out"];for(var e=this.cCanvas.data,f=e.width/2,h=e.height/2,i=this.get_parameter("pression")||100,a=cMath.linear_interpolation(a.A,a.B,100/i),i=0;i<a.length;i++)d.save(),d.translate(a[i].x-f,a[i].y-h),d.drawImage(e,
0,0,e.width,e.height),d.restore();d.restore();return!0};function Ctool_fill(a){a=a||{};a.className="Ctool_fill";a.label="bucket-fill";a.parameters={size:{label:"size",min:1,max:100,def:20,step:1}};Ctool.call(this,a,[])}Ctool_fill.prototype=Object.create(Ctool.prototype);Ctool_fill.prototype.constructor=new Ctool;
Ctool_fill.prototype.graph=function(a){var d=a.cSurface.layer_manager.special_layers.prefrag.cCanvas.data.getContext("2d"),e=a.cSurface.layer_manager.get();if(!e)return console.error("No layer selected"),!1;for(var e=e.getImageData(0,0,e.get_width(),e.get_height()),f=(new Cimage_analyse).adjacent_by_color(e,a.A),h=a.cToolbox.fg_color.color,i=0;i<f.length;i++)if(1==f[i]){var j=4*i;e.data[j]=h.r;e.data[j+1]=h.g;e.data[j+2]=h.b;e.data[j+3]=255}a.cMouse.minx=0;a.cMouse.miny=0;a.cMouse.maxx=e.width;a.cMouse.maxy=
e.height;d.putImageData(e,0,0);a.cGrapher.stop();return!0};function Cgraphit_message(a){a=a||{};a.className="Cmessage";a.label="message";Cobject.call(this,a,"cSurface cMouse cTool cToolbox points fgColor bgColor cGrapher index".split(" "))}Cgraphit_message.prototype=Object.create(Cobject.prototype);Cgraphit_message.prototype.constructor=new Cobject;var Egrapher_mode={continuous:1,endpoint:2};function Cgrapher(a){a=a||{};a.className="Cgrapher";a.label="grapher";Cobject.call(this,a,["parent"])}Cgrapher.prototype=Object.create(Cobject.prototype);
Cgrapher.prototype.constructor=new Cobject;Cgrapher.prototype.init=function(){this.parent||this.exception("no_parent_argument");this.reset_index();this.timer=null;this.mode=Egrapher_mode.continuous};Cgrapher.prototype.reset_index=function(){this.index=0};
Cgrapher.prototype._graph=function(a){var d=a.points.length;if(2>=d||this.index>=d-1)return!1;d=a.points[this.index+1];a.A=a.points[this.index];a.B=d;a.index=this.index;if(a.cTool.graph(a)&&(!this.last_redraw||Date.now()-this.last_redraw>1E3/60))this.last_redraw=Date.now(),a.cSurface.redraw(!0);this.index++};
Cgrapher.prototype.stop=function(){try{if(!this.timer)return console.warn("Grapher is not started"),!1;clearInterval(this.timer);this.timer=null;var a=this.parent.selected,d=a.cMouse,e=a.layer_manager.selected,f=a.layer_manager.special_layers.prefrag,h=e.cCanvas.data,i=this.parent.cToolbox.selected,j=this.parent.cToolbox.selected.parameters.size.value,k=j/2,l=d.maxx-d.minx+j,m=d.maxy-d.miny+j,n=d.minx-k;0>n&&(n=0);n+l>h.width&&(l=h.width-n);var p=d.miny-k;0>p&&(p=0);p+m>h.height&&(m=h.height-p);var q=
new Cgraphit_message({cSurface:a,cMouse:a.cMouse});i.post_graph(q,n,p,l,m,0,0,l,m)||e.drawImage(f.cCanvas.data,n,p,l,m,0,0);a.layer_manager.special_layers.prefrag=new Clayer({parent:a.layer_manager,label:"_prefrag",width:a.get_width(),height:a.get_height()});this.index=0;return!0}catch(r){return console.error(r),!1}};
Cgrapher.prototype.start=function(){if(this.timer)return console.error("Grapher already started"),!1;var a=this;if(!this.parent.cToolbox||!this.parent.cToolbox.selected)return this.send_trigger("error","no-tool-selectionned"),console.error("No tool selectionned!"),!1;var d=this.parent,e=new Cgraphit_message({cSurface:d.selected,cMouse:d.selected.cMouse,cTool:d.cToolbox.selected,cToolbox:d.cToolbox,points:d.selected.cMouse.points,fgColor:d.cToolbox.fg_color,bgColor:d.cToolbox.bg_color,cGrapher:this,
index:this.index});e.cTool.pre_graph(e);this.timer=window.setInterval(function(){a._graph(e)},5);return!0};var cDraw={circle:function(a){var d=a.dcanvas.getContext("2d");if(!d)return console.error("Cannot aquiere context"),!1;d.save();d.beginPath();d.arc(a.x,a.y,a.r,0,2*Math.PI,!0);a.fillStyle&&(d.fillStyle=a.fillStyle.to_rgba(),d.fill());a.lineWidth&&(d.lineWidth=a.lineWidth);a.strokeStyle&&(d.strokeStyle=a.strokeStyle.clone().set("a",1).to_rgba(),d.stroke());d.closePath();d.restore();return!0}};function Clicense(){this.logo="images/gplv3-88x31.png";this.text="license-gpl3.txt";this.rootElm=null;this.dialog_options={width:400}}
Clicense.prototype.dom_build=function(){if(this.rootElm)return this;var a=$('<div title="License"/>');a.addClass("about ");var d=$("<div />");d.addClass("group-license");var e=$("<img />");e[0].src=this.logo;d.append(e);d.append('<p>Source code: <a href="#code" onclick="window.open(\'http://github.com/shojs/graphit/\'); return false;">github</a></p>');d.append('<p>Documentation: <a href="#doc" onclick="window.open(\'http://github.com/shojs/graphit/wiki\');return false;">Wiki</a></p>');d.append('<p><img src="images/gimp/stock-wilber-eek-64.png">&nbsp;All icons comes from the <a href="http://www.gimp.org">Gimp</a> project.</p>');
d.append("<h6>License</h6>");e=$("<p />");e.addClass("text");e.append("                    GNU GENERAL PUBLIC LICENSE                       Version 3, 29 June 2007\n\n Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.");d.append(e);try{e.load(this.text)}catch(f){throw console.error("Cannot load full license",f),f;}e=document.createElement("button");$(e).append("Close");
$(e).button();$(e).click(function(){a.dialog("close")});d.append(e);a.append(d);this.rootElm=a;return this};Clicense.prototype.dom_get=function(){return this.dom_build().rootElm};function Cfrag(a){a.className="Cfrag";a.label="frag";Cobject.call(this,a,["parent","position","width","height","color"]);this.color||(this.color=new Ccolor(0,0,0,0));this.cCanvas=new Ccanvas({width:this.width,height:this.height,bg_color:this.color});(!this.position||!(this.position instanceof Cvector2d))&&this.exception("invalid_position")}Cfrag.prototype=Object.create(Cobject.prototype);Cfrag.prototype.constructor=new Cobject;
Cfrag.prototype.drawImage=function(a,d,e,f,h){var i=this.cCanvas.data,j=this.cCanvas.data.getContext("2d");try{j.drawImage(a,d,e,f,h,0,0,i.width,i.height)}catch(k){return console.error("Cannot draw to fragment",k),!1}return!0};var E_DRAWCOMPOSITION=Object({"source-in":"source-in","source-over":"source-over"});function Clayer(a){a=a||{};a.className="Clayer";a.label=a.label||"layer";a.position=a.position||new Cvector2d({x:0,y:0});a.composite_operation=a.composite_operation||Ecomposite_operation["source-over"];a.visible=void 0!=a.visible?a.visible:!1;a.need_redraw=!0;Cobject.call(this,a,"parent width height composite_operation need_redraw visible".split(" "))}Clayer.prototype=Object.create(Cobject.prototype);
Clayer.prototype.constructor=new Cobject;Clayer.prototype.init=function(){var a=this;if(!this.width||0>this.width||1920<this.width)console.error("gabou",this),this.exception("invalid_width",this.width);(!this.height||0>this.height||1280<this.height)&&this.exception("invalid_height",this.height);this.frags=[];this.cCanvas=new Ccanvas({width:this.width,height:this.height});this.bind_trigger(this,"redraw_preview",function(d){4<SHOJS_DEBUG&&console.debug("[Trigger/received]",d.type);a.redraw_preview()})};
Clayer.prototype.get_width=function(){return this.cCanvas.get_width()};Clayer.prototype.get_height=function(){return this.cCanvas.get_height()};Clayer.prototype.getImageData=function(a,d,e,f){return this.cCanvas.getImageData(a,d,e,f)};
Clayer.prototype.clone=function(){var a=this.cCanvas.data,d=new Clayer({parent:this.parent,label:this.label,composite_operation:this.composite_operation,width:this.width,height:this.height});d.visible=this.visible;d.cCanvas.getContext().drawImage(a,0,0,a.width,a.height);d.need_redraw=!1;d.rootElm=this.rootElm;return d};Clayer.prototype.discard_frag=function(){this.need_redraw=!0;return this.frags.pop()};Clayer.prototype.dom_get=function(){this.dom_build();return this.rootElm};
Clayer.prototype.set_visibility=function(a){this.visibility=a?!0:!1};Clayer.prototype.toggle_visibility=function(){return!0==this.visibility?this.set_visibility(!1):this.set_visibility(!0)};
Clayer.prototype.dom_build=function(){if(this.rootElm)return this;var a=this,d=document.createElement("li"),e=$(d);e.attr("id",this.uid);e.addClass("layer");d=$("<div/>");d.attr("id",this.uid);var f=$("<ul />");f.append('<li><a href="#'+this.guid(1)+'">layer</a></li>');f.append('<li><a href="#'+this.guid(2)+'">option</a></li>');f.append('<li><a href="#'+this.guid(3)+'">stats</a></li>');d.append(f);var f=$('<div id="'+this.guid(1)+'"/>'),h=new Cicon({name:"stock-eye",size:20,callback_click:function(){a.toggle_visibility();
a.send_trigger("update")}}),i=document.createElement("table"),i=$(i),j=$(document.createElement("tr")),k=$(document.createElement("td"));k.append(h.dom_get());j.append(k);k=$(document.createElement("td"));h="<span>Layer - "+this.label+"</span>";k.css("width","100px");k.css("text-overflow","ellipsis");k.append(h);k.editInPlace({callback:function(d,e){return a.label=e}});k.addClass("label");j.append(k);k=$(document.createElement("td"));k.addClass("preview");this.canvas_preview=h=document.createElement("canvas");
var l=100*(this.cCanvas.data.height/this.cCanvas.data.width);h.width=100;h.height=l;h=$(h);k.click(function(){$(this).parents(".group-layers").find(".layer").removeClass("selected");$(this).parents(".layer").addClass("selected");a.parent.select(a)});k.append(h);j.append(k);k=$(document.createElement("td"));h=new Cimage({src:"images/16x16_up.png",width:16,height:16,callback_click:function(){a.parent.move_up(a.uid)}});k.append(h.dom_get());h=new Cimage({src:"images/16x16_down.png",width:16,height:16,
callback_click:function(){a.parent.move_down(a.uid)}});k.append(h.dom_get());h=new Cimage({src:"images/16x16_trash.png",width:16,height:16,callback_click:function(){$(this).parents("li.layer")?(e.remove(),a.parent.remove(a)):console.error("Cannot remove layer element")}});j.append(k);k=$(document.createElement("td"));k.addClass("options");k.append(h.dom_get());j.append(k);i.append(j);f.append(i);d.append(f);f=$('<div id="'+this.guid(2)+'"/>');f.append("<p>Layer option</p>");d.append(f);var m=$('<div id="'+
this.guid(3)+'"/>');m.append('<p>Total fragment: <span id="'+this.guid("total-fragment")+'">'+this.frags.length+"</span></p>");this.bind_trigger(this,"redraw_preview",function(){m.find("span").empty().append(a.frags.length)});d.append(m);e.append(d);d.tabs();this.rootElm=e;return this};Clayer.prototype.redraw_preview=function(){var a=this.canvas_preview.getContext("2d"),d=this.cCanvas.data;a.clearRect(0,0,d.width,d.height);a.drawImage(d,0,0,d.width,d.height,0,0,this.canvas_preview.width,this.canvas_preview.height)};
Clayer.prototype.redraw=function(a){"boolean"===typeof a&&(this.need_redraw=a);if(!this.need_redraw)return!1;a=this.cCanvas.getContext();a.clearRect(0,0,this.cCanvas.data.width,this.cCanvas.data.height);"compositeOperation"in this&&(a.compositeOperation=this.compositeOperation);for(var d=this.cCanvas.data.width,e=this.cCanvas.data.height,f=0;f<this.frags.length;f++){var h=this.frags[f],i=h.cCanvas.data,j=i.height,k=i.width,l=h.position.x;0>l?l=0:l+k>d&&(k=d-l);var m=h.position.y;0>m?m=0:m+j>e&&(j=
e-m);a.save();a.beginPath();a.rect(l,m,k,j);a.clip();a.globalCompositeOperation=h.downCompositeOperation?h.downCompositeOperation:"source-over";a.drawImage(i,0,0,k,j,l,m,k,j);a.restore()}this.send_trigger("redraw_preview");this.need_redraw=!1;return!0};Clayer.prototype.clear=function(){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);this.frags=[]};
Clayer.prototype.drawImage=function(a,d,e,f,h,i,j,k){i=new Cfrag({parent:this,position:new Cvector2d({x:d,y:e}),width:f,height:h});i.drawImage(a,d,e,f,h,0,0);this.frags.push(i);k&&(i.downCompositeOperation=k)};Clayer.prototype.copy=function(a){this.drawImage(a.src,0,0,a.src.width,a.src.height,0,0)};Clayer.prototype.to_json=function(){return{label:this.data,data:this.cCanvas.data.toDataURL()}};function Clayer_manager(a){var d=this,a=a||{};a.className="Clayer_manager";a.label="layermanager";Cobject.call(this,a,["parent"]);this.parent||this.exception("no_parent_parameter");this.layers=[];this.special_layers={};this.selected=null;this.dom_build();this.bind_trigger(this,"update",function(){d.redraw()});var a=this.parent.get_width(),e=this.parent.get_height();this.add(new Clayer({parent:this,label:"_stack_up",width:a,height:e}));this.add(new Clayer({parent:this,label:"_stack_down",width:a,height:e}));
this.add(new Clayer({parent:this,label:"_grid",width:a,height:e}));this.add(new Clayer({parent:this,label:"background",width:a,height:e}))}Clayer_manager.prototype=Object.create(Cobject.prototype);Clayer_manager.prototype.constructor=new Cobject;Clayer_manager.prototype.build_layer_stack=function(a){this.special_layers.stack_down=this.layer_stack(0,a-1);this.special_layers.stack_up=this.layer_stack(a+1,this.layers.length-1)};
Clayer_manager.prototype.add=function(a){a.parent=this;var d=this;if(!(a instanceof Clayer))return console.error("Layer manager need Clayer object"),null;var e=RegExp(/^_(.*)/).exec(a.label);e?(a.label="layer-"+e[1],this.special_layers[e[1]]=a):this.layers.push(a);if(!e&&this.rootElm){var e=this.rootElm.find(".group-layers"),f=$(a.dom_get(this.layers.length-1));e.prepend(f)}this.selected||(this.selected=a);this.bind_trigger(a,"update",function(){d.redraw()});this.send_trigger("update");return a};
Clayer_manager.prototype.layer_stack=function(a,d){if(a>d)return null;for(var e=this.parent.get_width(),f=this.parent.get_height(),e=new Clayer({parent:this,label:"stack",width:e,height:f}),f=e.cCanvas.getContext(),h,i=a;i<=d;i++)h=this.layers[i].cCanvas.data,f.drawImage(h,0,0,h.width,h.height);return e};Clayer_manager.prototype.exists=function(a){for(var d=0,e=!1,d=0;d<this.layers.length;d++)if(this.layers[d]==a){e=!0;break}return e?d:null};
Clayer_manager.prototype.remove=function(a){var d=this.selected,e=this.exists(a);d==a&&1<e&&(d=this.layers[e-1]);void 0===e&&console.error("Cannot remove undefined element");this.layers.splice(e,1);this.select(d);this.parent.redraw(!0)};Clayer_manager.prototype.get=function(a){return!a||"__selected__"==a?this.selected:cMath.isint(a)?this.layers[a]:this.special_layers[a]};Clayer_manager.prototype.get_index_by_uid=function(a){for(var d=0;d<this.layers.length;d++)if(this.layers[d].uid==a)return d;return null};
Clayer_manager.prototype.move_down=function(a){a=this.get_index_by_uid(a);if(void 0===a||1>=this.layers.length||1>a)return console.error("Can't move layer up"),!1;var d=this.layers[a-1];this.layers[a-1]=this.layers[a];this.layers[a]=d;this.select(this.selected);this._build_layer_preview(".group-layers");this.send_trigger("update");return!0};
Clayer_manager.prototype.move_up=function(a){if(1==this.layers.length)return!1;a=this.get_index_by_uid(a);if(void 0===a||a>=this.layers.length-1||1>=this.layers.length)return console.error("Can't move layer up"),!1;var d=this.layers[a+1];this.layers[a+1]=this.layers[a];this.layers[a]=d;this.select(this.selected);this._build_layer_preview(".group-layers");this.send_trigger("update");return!0};
Clayer_manager.prototype.select=function(a){a=this.exists(a);if(void 0===a||0>a||a>this.layers.length)return console.error("Layer index out of range: "+a),!1;this.build_layer_stack(a);this.selected=this.layers[a];this.send_trigger("update");return!0};
Clayer_manager.prototype.dom_build=function(){var a=this,d=$("<div />");d.attr("title","Layer manager");var e=$("<div />");$("<div />");var f=new Cicon({name:"stock-layer",size:24,width:16,height:16,title:"Create new layer",callback_click:function(){a.add(new Clayer({parent:a,width:a.parent.get_width(),height:a.parent.get_height()}))}});d.append(f.dom_get());f=$("<ul />");f.addClass("group-layers ui-widget-content");d.append(f);d.append(e);this.rootElm=d;return this};
Clayer_manager.prototype._build_layer_preview=function(a){a=$(a);a.find(".layer").detach();for(var d=this.layers.length-1;0<=d;d--)this.layers[d].redraw(!0),a.append(this.layers[d].dom_get(1))};Clayer_manager.prototype.dom_exists=function(a){var d=!1,e;for(e=0;e<this.layers.length;e++)if(this.layers[e].rootElm=a){d=!0;break}return d?e:null};Clayer_manager.prototype.redraw=function(a){for(var d=0;d<this.layers.length;d++)this.layers[d].redraw(a)};function Csurface(a){var d=this,a=a||{};a.className="Csurface";a.label="surface";a.parameters={zoom:{label:"zoom",min:-100,max:100,def:0,step:1,autoSave:!1,callback_slide:function(){console.log("slidinggggggg",this)}}};Cobject.call(this,a,["width","height","label"]);a=this.width||0;a=cMath.clamp(1,a,1920);this.width!=a&&this.exception("invalid_width",this.width);a=this.height||0;a=cMath.clamp(1,this.height,1920);this.height!=a&&this.exception("invalid_height",this.height);this.need_redraw=!1;this.cCanvas=
new Ccanvas({width:this.width,height:this.height});this.cCanvas.clear(new Ccolor(0,0,0,0));this.layer_manager=new Clayer_manager({parent:this});this.layer_manager.add(new Clayer({parent:this.layer_manager,label:E_LAYERLABEL.mouse,width:this.width,height:this.height}));this.layer_manager.add(new Clayer({parent:this.layer_manager,label:E_LAYERLABEL.prefrag,width:this.width,height:this.height}));this.layer_manager.add(new Clayer({parent:this.layer_manager,width:this.width,height:this.height}));this.layer_manager.select(this.layer_manager.layers[0]);
this.bind_trigger(this.layer_manager,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);d.redraw(1)});this.cMouse=new Cmouse_tracker({parent:this,callback_move:function(){console.log("mouse move")},callback_track:function(a,f){$(d.cMouse.rootElm).find(".var-x").empty().append(a);$(d.cMouse.rootElm).find(".var-y").empty().append(f)}});this.cGrid=new Cgrid({parent:this,callback_slide:function(a){this.set(a);console.log("slide");this.send_trigger("update")},callback_change:function(a){this.set(a);
console.log("Change");this.send_trigger("update")}});this.bind_trigger(this.cGrid,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);d.update_grid()});this.bind_trigger(this,"update",function(){d.redraw(1)});this.bind_trigger(this,"show",function(a,f){f||widget_factory(d.dom_get(),{width:d.cCanvas.get_width()+100,zIndex:0,stack:!0}).show()});this.update_grid();return this}Csurface.prototype=Object.create(Cobject.prototype);Csurface.prototype.constructor=new Cobject;
Csurface.prototype.set_current_layer=function(a){this.layer_manager.select(a)};Csurface.prototype.update_grid=function(){var a=this.layer_manager.get("grid");a.cCanvas.getContext().clearRect(0,0,a.cCanvas.data.width,a.cCanvas.data.height);this.cGrid.get_parameter("visibility")&&this.cGrid.draw(a.cCanvas.data,0,0,this.cCanvas.data.width,this.cCanvas.data.height);this.need_redraw=!0;this.send_trigger("update")};
Csurface.prototype.dom_build=function(){var a=this,d=$('<div title="(Ctrl-z) Undo"/>');d.addClass("surface");var e=$("<div/>"),f=$(this.cCanvas.data);f.width=this.width;f.height=this.height;f.addClass("canvas");f.attr("tabindex",0);f.mousedown(function(d){a.callback_mousedown(d,a)});f.mouseup(function(d){a.callback_mouseup(d,a)});f.mousemove(function(d){a.callback_mousemove(d,a)});f.mouseout(function(){a.cMouse.is_pushed()&&(a.cMouse.paused=!0)});f.mouseover(function(){a.cMouse.is_pushed()&&(a.cMouse.paused=
!1)});f.mouseenter(function(){a.send_trigger("surface_selected",a)});e.append(f);d.append(e);d.append(e);this.rootElm=d;return this};Csurface.prototype.undo=function(){this.layer_manager.selected.discard_frag();this.layer_manager.selected.redraw();this.redraw(!0)};
Csurface.prototype.redraw=function(a){if(!this.need_redraw&&!a)return!1;if(!this.layer_manager.get())return console.warn("No layer selected"),!1;var d=this.cCanvas.data,e=d.getContext("2d");e.save();var f=this.get_parameter("zoom");0!=f&&(e.translate(d.width/2,d.height/2),e.scale(f,f));e.clearRect(0,0,d.width,d.height);void 0!=this.layer_manager.special_layers.stack_down&&e.drawImage(this.layer_manager.special_layers.stack_down.cCanvas.data,0,0,d.width,d.height);this.layer_manager.selected.redraw(a);
e.drawImage(this.layer_manager.selected.cCanvas.data,0,0,d.width,d.height);"down_composite_operation"in this.layer_manager.special_layers.prefrag&&(e.globalCompositeOperation=this.layer_manager.special_layers.prefrag.down_composite_operation);e.drawImage(this.layer_manager.special_layers.prefrag.cCanvas.data,0,0,d.width,d.height);"down_composite_operation"in this.layer_manager.special_layers.prefrag&&(e.globalCompositeOperation="source-over");void 0!=this.layer_manager.special_layers.stack_up&&e.drawImage(this.layer_manager.special_layers.stack_up.cCanvas.data,
0,0,d.width,d.height);"cGrid"in this&&this.cGrid.isVisible&&e.drawImage(this.layer_manager.special_layers.grid.cCanvas.data,0,0,d.width,d.height);e.restore();this.send_trigger("redraw_preview",this);this.need_redraw=!1;return!0};Csurface.prototype.clear=function(){for(var a=0;a<this.layer_manager.layers.length;a++)this.layer_manager.layers[a].clear();this.need_redraw=!0;this.send_trigger("update")};Csurface.prototype.get_width=function(){return this.cCanvas.data.width};
Csurface.prototype.get_height=function(){return this.cCanvas.data.height};Csurface.prototype.callback_mousedown=function(){if(this.cMouse.is_pushed())return console.warn("Mouse already pushed"),!1;this.cMouse.push();this.cGraphit.cGrapher.start();return!0};Csurface.prototype.callback_mouseup=function(){if(!this.cMouse.is_pushed())return console.warn("Mouse not pushed"),!1;this.cGraphit.cGrapher.stop();this.redraw(!0);this.cMouse.release();return!0};
Csurface.prototype.callback_mousemove=function(a,d){var e=$(d.cCanvas.data).offset();this.cMouse.move(a.pageX-e.left,a.pageY-e.top)};Csurface.prototype.attach_graphit=function(a){if(!a||!(a instanceof Cgraphit))return console.error("Can't attach null or none Ctoolbox instance"),!1;this.cGraphit=a};Csurface.prototype.save_as_json=function(){window.open(this.cCanvas.data.toDataURL());return data};function Csurface_workspace(a){a=a||{};a.className="Csurface_workspace";a.label="Workspace";Cobject.call(this,a,[])}Csurface_workspace.prototype=Object.create(Cobject.prototype);Csurface_workspace.prototype.constructor=new Cobject;Csurface_workspace.prototype.init=function(a){var d=this;try{this.cSurface=new Csurface(a)}catch(e){throw console.error("Cannot create surface"),e;}this.bind_trigger(this,"show",function(){d.show()})};
Csurface_workspace.prototype.dom_build=function(){var a=this,d=$('<div class="graphit-workspace"/>'),e=$('<div class="navbar"/>');e.append((new Cicon({name:"stock-layers",size:24,width:32,height:32,label:T("layers"),callback_click:function(){a.cSurface.layer_manager.dom_get().dialog({autoOpen:!0});return!1}})).dom_get());e.append((new Cicon({name:"stock-image",size:24,width:32,height:32,label:T("save"),callback_click:function(){a.__save_dialog();return!1}})).dom_get());"cGraphitAuth"in window&&!window.cGraphitAuth.is_disable()&&
e.append((new Cicon({path:"preferences",name:"folders",width:32,height:32,label:T("open"),callback_click:function(){a.__load_dialog();return!1}})).dom_get());d.append(e);d.append(this.cSurface.dom_get());e=$("<div />");d.append(e);this.rootElm=d;return this};
Csurface_workspace.prototype.__save_dialog=function(){$("<div />").attr("title","save");var a=this.cSurface.cCanvas.clone(),d=window.open(null,"graphit-save","resizable=yes, scrollbars=yes, titlebar=yes, width=300, height=300 top=10, left=10",!1),e=$(d.document.head);0==e.find("title").length&&e.append("<title>GraphIt - "+T("save_image")+"</title>");var f=$('<link id="id-graphit-css" type="text/css" rel="stylesheet" href="css/style.css"/>');0==e.find("#id-graphit-css").length&&e.append(f);d=$(d.document.body);
d.empty();e=$('<div class="graphit-window group" />');e.append("<h3>"+T("right_click_to_save")+"<h3/>");f=new $("<img />");f.attr("src",a.data.toDataURL());f.attr("width",200);f.attr("title","graphit-image");f.attr("alt","graphit-image");f.css("background-image",'url("img/grid-40x40.png")');e.append(f);d.append(e)};
Csurface_workspace.prototype.__load_dialog=function(){var a=this;try{return this.get_widget("load").dialog("open")}catch(d){console.warn("Can't get <<load>> widget")}var e=$("<div />"),f=$('<input type="url" width="200" value="http://1.bp.blogspot.com/_cmrGYcwOHPE/TLXcloz0rFI/AAAAAAAAAas/Tv98tJD7qO0/s1600/plop1.gif"/>'),h=$("<button>"+T("load")+"</button>");h.click(function(){$(this).parent().dialog("close");var d=$(this).parent().find("input");loc=window.location;var e=loc.pathname.split("/"),e=
e.slice(0,e.length-1).join("/"),e=loc.protocol+"//"+loc.hostname+"/"+e+"php/DataURL/";console.log(e);try{cGraphitAuth.get("verifiedEmail"),$.getImageData({url:d.attr("value"),server:e,callback:"?",success:function(d){var e=new Clayer({width:a.cSurface.cCanvas.data.width,height:a.cSurface.cCanvas.data.height,label:"Web Image"});e.copy({src:d});a.cSurface.layer_manager.add(e)},error:function(e,f){console.error("Cannot load image",d.attr("value"));a.exception("cannot_load_image",f,{dialog:!0})}})}catch(f){widget_exception(f)}console.log("input",
d,d.attr("value"))});e.append(f);e.append(h);e.attr("title",T("load_image"));this.add_widget("load",e);e.dialog()};Csurface_workspace.prototype.show=function(){this.dom_get()};function Cgrid(a){a.className="Cgrid";a.label="grid";Cobject.call(this,a,["parent","callback_slide","callback_change","label"])}Cgrid.prototype=Object.create(Cobject.prototype);Cgrid.prototype.constructor=new Cobject;
Cgrid.prototype.init=function(){this.color=this.color||new Ccolor(0,0,0,1);this.isVisible=this.isVisible||!0;var a=this,d=function(){a.send_trigger("update")};this.parameters={width:new Cparameter_numeric({parent:this,label:"width",min:1,max:100,def:100,step:1,callback_change:d,callback_slide:d}),height:new Cparameter_numeric({parent:this,label:"height",min:1,max:100,def:100,step:1,callback_change:d,callback_slide:d}),lineWidth:new Cparameter_numeric({parent:this,label:"lineWidth",min:1,max:10,def:1,
step:1,callback_change:d,callback_slide:d}),visibility:new Cparameter_checkbox({parent:this,type:Eparameter_type.checkbox,label:"visibility",def:!1,callback_change:d})};this.label="grid";this.rootElm=null};
Cgrid.prototype.draw=function(a,d,e,f,h){d=a.getContext("2d");d.save();d.beginPath();f=this.get_parameter("width");h=this.get_parameter("height");for(e=f+1;e<a.width;e+=f)d.moveTo(e,0),d.lineTo(e,a.height);for(f=h+1;f<a.height;f+=h)d.moveTo(0,f),d.lineTo(a.width,f);d.closePath();d.strokeStyle=this.color.to_rgba();d.lineWidth=this.get_parameter("lineWidth");d.stroke();d.restore()};
Cgrid.prototype.dom_build=function(){var a=$("<div />");a.attr("title",this.label);a.addClass("grid");var d=$("<div />");d.addClass("ui-widget-content");for(label in this.parameters)a.append(this.parameters[label].dom_get());a.append(d);this.rootElm=a;return this};function Ctoolbox_preview(a){var d=this;a.className="Ctoolbox_preview";a.label="toolboxpreview";Cobject.call(this,a,["parent"]);this.bind_trigger(this,"update",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);a=d.rootElm.find("canvas")[0].getContext("2d");a=d.parent.fg_color.color.clone().inverse();a.a=1;d.cCanvas.clear(a);var a=d.cCanvas.getContext(),f=d.parent.brush_manager.selected.cCanvas.data,h=d.parent.selected.get_parameter("size"),i=h>d.cCanvas.get_width()?d.cCanvas.get_width():
h,j=h>d.cCanvas.get_height()?d.cCanvas.get_height():h,h=(d.cCanvas.get_width()-h)/2;a.drawImage(f,0,0,f.width,f.height,h,h,i,j)})}Ctoolbox_preview.prototype=Object.create(Cobject.prototype);Ctoolbox_preview.prototype.constructor=new Cobject;Ctoolbox_preview.prototype.init=function(){this.cCanvas=new Ccanvas({parent:this,width:100,height:100,src:"images/loading_toolbar_brush.png"})};
Ctoolbox_preview.prototype.dom_build=function(){var a=$("<div />");a.addClass("toolbox-preview");var d=$("<div />");d.append(this.cCanvas.dom_get());a.append(d);this.rootElm=a;return this};function Ctoolbox_colorpicker(a,d){d.className="Ctoolbox_colorpicker";Cobject.call(this,d,["parent","label","callback_onchange"]);if(a&&!(a instanceof Ccolor))return console.error("color parameter is not an instance of Ccolor"),null;this.color=a?a:new Ccolor;this.rootElm=null;this.cCanvas=new Ccanvas({width:32,height:32});this.ctx=this.cCanvas.getContext();this.clear(this.color)}Ctoolbox_colorpicker.prototype=Object.create(Cobject.prototype);Ctoolbox_colorpicker.prototype.constructor=new Cobject;
Ctoolbox_colorpicker.prototype.clear=function(a){this.cCanvas.clear(a)};Ctoolbox_colorpicker.prototype.to_rgba=function(){return this.color.to_rgba()};
Ctoolbox_colorpicker.prototype.dom_build=function(){var a=this;if(this.rootElm)return this;var d=document.createElement("div"),d=$(d),e=document.createElement("canvas");e.setAttribute("width",32);e.setAttribute("height",32);e.setAttribute("alt",this.label);e.setAttribute("title",this.label);this.elmImage=e;d.append(e);var f=e.getContext("2d"),h=this.cCanvas.data;f.drawImage(h,0,0,h.width,h.height);var i=function(d){a.color.set_rgb(d);a.clear(a.color);f.drawImage(h,0,0,h.width,h.height);a.send_trigger("color_selected")};
$(e).ColorPicker({onChange:function(a,d,e){i.call(this,e)},onSubmit:function(a,d,e){i.call(this,e)},zIndex:10});this.rootElm=d;return this};function Ctoolbox(a){var d=this;a.className="Ctoolbox";a.label="toolbox";Cobject.call(this,a,["parent"]);this.elmOptions=this.elmPreview=null;this.dialog_options={modal:!1,width:250,position:"right top",stack:!0};this.bind_trigger(this.fg_color,"color_selected",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);d.update()});this.bind_trigger(this.bg_color,"color_selected",function(a){4<SHOJS_DEBUG&&console.log("[Trigger/received]",a.type);d.update()});this.bind_trigger(this,"switch_color",
function(){d.switch_color()})}Ctoolbox.prototype=Object.create(Cobject.prototype);Ctoolbox.prototype.constructor=new Cobject;
Ctoolbox.prototype.init=function(){var a=this;this.selected=null;this.tools=[];this.preview=new Ctoolbox_preview({parent:this});this.fg_color=new Ctoolbox_colorpicker(new Ccolor(255,255,255,1),{parent:this,callback_onchange:function(){this.send_trigger("update",a)},label:T("foreground_color")});this.bind_trigger(this.fg_color,"update",function(){a.update()});this.bg_color=new Ctoolbox_colorpicker(new Ccolor(0,0,0,1),{parent:this,label:"Background color",callback_onchange:function(){this.send_trigger("update",
a)},label:T("background_color")});this.bind_trigger(this.bg_color,"update",function(){a.update()});this.brush_manager=new Cbrush_manager({parent:this});this.bind_trigger(this.brush_manager,"update",function(){a.update()});this.load(this.olist);this.dom_build()};Ctoolbox.prototype.select_tool_by_name=function(a){var d=this;return cEach(this.tools,function(e,f){f.label==a&&(d.select_tool(f),this.stop(),this.ret=!0);return!1})};
Ctoolbox.prototype.load=function(){var a=this,d=function(d){a.bind_trigger(d,"update",function(){a.preview.send_trigger("update")});a.tools.push(d)},e=new Ctool_pencil({parent:this});d.call(this,e);this.selected=e;e=new Ctool_paintbrush({parent:this});d.call(this,e);e=new Ctool_eraser({parent:this});d.call(this,e);e=new Ctool_fill({parent:this});d.call(this,e)};
Ctoolbox.prototype.update=function(){this.brush_manager.selected.callback.update.call(this.brush_manager.selected);this.selected.update();this.preview.send_trigger("update")};
Ctoolbox.prototype.select_tool=function(a){if(void 0==a)return console.warn("Can't select undefined tool"),!1;var d=$(a.rootElm);d.parents(".group-tools").find(".tool").removeClass("selected");d.children(".tool").addClass("selected");d=d.parents(".toolbox").find(".group-options");d.children("div").detach();d.append(a.dom_build_options());this.selected=a;this.update();return!0};
Ctoolbox.prototype.switch_color=function(){var a=this.fg_color;this.fg_color=this.bg_color;this.bg_color=a;a=this.rootElm.find(".colorpicker-colors");a.children(".colorpicker").detach();this.dom_build_colorpickers(a);this.send_trigger("update_foreground_color")};Ctoolbox.prototype.dom_build_colorpickers=function(a){a.append(this.fg_color.dom_get());a.append(this.bg_color.dom_get())};
Ctoolbox.prototype.dom_build=function(){var a=this,d=$('<div title="Toolbox"/>');d.addClass("toolbox");var e=$("<div />");e.addClass("group group-tools ui-widget-content");for(var f=0;f<this.tools.length;f++){var h=this.tools[f];h.bind_trigger(h,"tool_selected",function(d,e){if(!(e instanceof Ctool))return console.error("Trigger tool_selected must pass a Ctool argument"),!1;a.select_tool(e);return!0});var i=h.dom_get();this.selected==h&&h.rootElm.children(".tool").addClass("selected");e.append(i)}d.append(e);
e=$("<div/>");e.addClass("ui-widget-content group-colorpicker");f=$("<div/>");f.addClass("ui-widget-content colorpicker-colors");this.dom_build_colorpickers(f);e.append(f);e.append($((new Cicon({name:"stock-default-colors",size:12,callback_click:function(){a.send_trigger("switch_color");a.update()},label:T("switch_color")})).dom_get().addClass("switch")));d.append(e);e=$("<div/>");e.addClass("group-preview ui-widget-content");e.append(this.preview.dom_get());d.append(e);e=$("<div />");e.addClass("group-options ui-widget-content");
d.append(e);e=$("<div />");e.addClass("group-brushmanager ui-widget-content");e.append(this.brush_manager.dom_get());d.append(e);this.rootElm=d;return this};function Cbinary_file(a){a=a||{};a.className="Cbinary_file";a.label="binaryfile";this.headers=[];this.FH={};Cobject.call(this,a,["src","callback_success","callback_error","responseType"]);this.responseType=this.responseType||"arraybuffer";this.response=null;this.loaded=!1;this.error="";this.src&&this.load(this.src)}Cbinary_file.prototype=Object.create(Cobject.prototype);Cbinary_file.prototype.constructor=new Cobject;Cobject.prototype.set_src=function(){};
Cobject.prototype.load=function(a){if(!a)return console.error("Trying to load undefined src"),null;4<SHOJS_DEBUG&&console.log("Loading file: "+a);this.src=a;var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";var e=this;d.onload=function(){e.response=this;"success"in e.callback&&e.callback.success.call(e,this)};d.onerror=function(){console.error(this.className+" failed to load file",this.src);"error"in e.callback&&e.callback.error(e,this)};d.send()};
Cobject.prototype.header=function(a){return!(a in this.FH)?(console.error("No property <<",a,">> in header"),""):this.headers[this.FH[a]].value};function Cfile_GBR(a){Cbinary_file.call(this,a);"success"in this.callback&&(this.callback._success=this.callback.success);"error"in this.callback&&(this.callback._error=this.callback.error);this.callback.success=this._success;this.callback.error=this._error}Cfile_GBR.prototype=Object.create(Cbinary_file.prototype);Cfile_GBR.prototype.constructor=new Cbinary_file;
Cfile_GBR.prototype.init=function(){this.loaded=!1;this.magic_number=1195986256;this.cCanvas=null;this.headers=[{type:"uint32",label:"header_size"},{type:"uint32",label:"version"},{type:"uint32",label:"width"},{type:"uint32",label:"height"},{type:"uint32",label:"bytes"},{type:"uint32",label:"magic_number"},{type:"uint32",label:"spacing"}];this.FH={header_size:0,version:1,width:2,height:3,bytes:4,magic_number:5,spacing:6}};
Cfile_GBR.prototype._success=function(a){this.loaded=!1;if(this.parse_response(a))return this.loaded=!0,"_success"in this.callback&&this.callback._success.call(this,a),!0;this.init();return!1};
Cfile_GBR.prototype.parse_response=function(a){var d=this.FH;10<SHOJS_DEBUG&&console.log("[File/GBR] Parsing header",this.src);for(var a=new DataView(a.response,0),e=0,f=0;f<this.headers.length;f++)this.headers[f].value=a.getInt32(e),10<SHOJS_DEBUG&&console.log(this.headers[f].label,this.headers[f].value),e+=4;if(this.headers[d.magic_number].value!=this.magic_number)return console.error("Trying to load file that is not a GIMP GBR (Brush)"),!1;for(var f=this.headers[d.header_size].value,h="",i=0;i<
f;i++)h+=String.fromCharCode(a.getInt8(e)),e+=1;this.name=h;f=null;f=this.headers[d.bytes].value;if(4==f)label_type="RGBA",f=this._canvas_store_rgba;else if(1==f)label_type="GRAYSCALE",f=this._canvas_store_grayscale;else return console.log("Dunnot know how parsing format with bytes => ",f),!1;d=new Ccanvas({width:this.headers[d.width].value,height:this.headers[d.height].value});d.clear(new Ccolor(0,0,0,1));for(var h=d.getContext("2d"),i=h.getImageData(0,0,d.width,d.height),j=0;e<a.byteLength;e++)j+=
f(i,a,j,e);h.putImageData(i,0,0);this.cCanvas=d;return!0};Cfile_GBR.prototype._canvas_store_rgba=function(a,d,e,f){a.data[e]=d.getUint8(f);return 1};Cfile_GBR.prototype._canvas_store_grayscale=function(a,d,e,f){a.data[e]=d.getUint8(f);a.data[e+1]=d.getUint8(f);a.data[e+2]=d.getUint8(f);a.data[e+3]=255;return 4};Cfile_GBR.prototype.dom_build=function(){var a=$("<div />");this.loaded?a.append(this.cCanvas.dom_get()):a.append("<p>Failed to load Gimp gbr file: "+this.src+"</p>");this.rootElm=a;return this};
Cfile_GBR.prototype._error=function(){this.init();"_error"in this.callback&&this.callback._error.call(this)};var Ebrush_type=new Cenum({js:1,gbr:2});function Cbrush(a){a.className="Cbrush";a.label="brush";Cobject.call(this,a,["parent","name","type"])}Cbrush.prototype=Object.create(Cobject.prototype);Cbrush.prototype.constructor=new Cobject;
Cbrush.prototype.init=function(a){if(!this.type||!this.name)return console.error("Cbrush need <<type>> and <<name>> parameter"),!1;if(this.type==Ebrush_type.js)this._load_js(a);else if(this.type==Ebrush_type.gbr)console.log("Parsing Gimp Brush"),this._load_gbr(a);else return console.error("Unknow Cbrush type",this.type),!1;return this.init_canvas(a)};Cbrush.prototype.init_canvas=function(a){a=new Ccanvas({width:a.data.width,height:a.data.height});a.clear(new Ccolor(0,0,0,0));this.cCanvas=a};
Cbrush.prototype.update=function(){this.callback.update.call(this,this.parent)};Cbrush.prototype._load_js=function(a){if(!("callback_update"in a.data))return console.error("Javascript brush must contain a callback_update function"),!1;this.callback.update=a.data.callback_update;return!("width"in a.data)||!("height"in a.data)?(console.error("Javascript brush need width and height property"),!1):!0};Cbrush.prototype._load_gbr=function(){};
Cbrush.prototype.dom_build=function(){var a=this,d=$("<div />"),e=$("<div />");e.addClass("group-brush group");e.append("<label>"+Ebrush_type.key_by_value(this.type)+" / "+this.name+"</label>");e.append(this.cCanvas.dom_get());d.append(e);d.click(function(){a.send_trigger("brush_selected",a);$(this).parents(".group-brushmanager").find(".group-brush").removeClass("selected");$(this).children(".group-brush").addClass("selected")});this.rootElm=d;return this};function Cbrush_manager(a){a=a||{};a.className="Cbrush_manager";a.label="brushmanager";this.brushes=[];this.selected=null;Cobject.call(this,a,["parent"])}Cbrush_manager.prototype=Object.create(Cobject.prototype);Cbrush_manager.prototype.constructor=new Cobject;
Cbrush_manager.prototype.init=function(){this.add(new Cbrush({parent:this,type:Ebrush_type.js,name:"circle",data:CTOOL_brushes.circle}));this.add(new Cbrush({parent:this,type:Ebrush_type.js,name:"rectangle",data:CTOOL_brushes.rectangle}));this.add(new Cbrush({parent:this,type:Ebrush_type.js,name:"scircle",data:CTOOL_brushes.scircle}))};
Cbrush_manager.prototype.dom_build=function(){var a=this,d=$("<div />");d.attr("id",this.guid());d.attr("title",this.label);var e=$("<div />");cEach(this.brushes,function(d,h){var i=h.dom_get();a.selected==h&&i.find(".group-brush").addClass("selected");e.append(i)});d.append(e);this.rootElm=d;return this};
Cbrush_manager.prototype.add=function(a){var d=this;if(this.exists(a))return console.error("This brush is already present"),!1;this.selected||(this.selected=a);this.bind_trigger(a,"brush_selected",function(a,f){if(!(f instanceof Cbrush))return console.error("Trigger brush_selected must reture a brush",a,f),!1;d.selected=f;d.selected.update();d.send_trigger("update")});this.brushes.push(a);this.send_trigger("update");return!0};
Cbrush_manager.prototype.exists=function(a){cEach(this.brushes,function(d){if(d.type==a.type&&d.name==a.name)return!0});return!1};function Cgraphit(a){a=a||{};a.className="Cgraphit";a.label="graphit";a.widgets={};this.surfaces=[];this.selected=null;Cobject.call(this,a,["widgets"]);this.dialog_options={position:"right top"};this.dom_get();this.surface_create({parent:this,width:400,height:400})}Cgraphit.prototype=Object.create(Cobject.prototype);Cgraphit.prototype.constructor=new Cobject;
Cgraphit.prototype.init=function(){var a=this;this.bind_trigger(this,"create_surface",function(d,f){a.surface_create(f)});this.bind_trigger(this,"display_new_surface",function(){a.dialog_new_surface().dialog("open").dialog("moveToTop")});this.bind_trigger(this,"display_widget",function(d,f){a.get_widget(f).dialog("open").dialog("moveToTop")});this.wJquerytheme=new Cjquery_theme;this.wAbout=new Clicense;this.cMenu=new Cmenu({parent:null,type:"jquery",label:"graphit_menu",entries:{files:{label:T("menu_file"),
entries:{new_surface:{label:T("menu_new_surface"),callback_click:function(){a.send_trigger("display_new_surface")}}}},edition:{label:T("menu_edition"),entries:{toolbox:{label:T("menu_toolbox"),callback_click:function(){a.send_trigger("display_widget",a.cToolbox)}}}},help:{label:T("menu_help"),entries:{theme:{label:T("menu_theme"),callback_click:function(){a.send_trigger("display_widget",a.wJquerytheme)}},about:{label:T("menu_about"),callback_click:function(){a.send_trigger("display_widget",a.wAbout)}}}}}});
this.cToolbox=new Ctoolbox(CTOOL_tools,{parent:this});this.bind_trigger(this.cToolbox,"update",function(){});this.cGrapher=new Cgrapher({parent:this});this.bind_trigger(this.cGrapher,"update",function(){});this.keybindings={n:{label:"pen",callback:function(){a.cToolbox.select_tool_by_name("pen");return!1}},p:{label:"brush",callback:function(){a.cToolbox.select_tool_by_name("brush");return!1}},"Shift+e":{label:"eraser",callback:function(){a.cToolbox.select_tool_by_name("eraser");return!1}},"Ctrl+z":{label:"undo",
callback:function(d){d.preventDefault();d.stopPropagation();d.stopImmediatePropagation();if(!a.selected)return console.warn("No surface selected to call undo"),!1;a.selected.undo();return!1}}};for(var d in this.keybindings)$(document).bind("keydown",d,this.keybindings[d].callback);this.send_trigger("display_widget",this.cToolbox)};
Cgraphit.prototype.get_widget=function(a){"dom_get"in a||this.exception("method_object_missing","dom_get");if(a.label in this.widgets)return this.widgets[a.label];var d={closeOnEscape:!0,modal:!0};if("dialog_options"in a)for(label in a.dialog_options)d[label]=a.dialog_options[label];d=a.dom_get().dialog(d);return this.widgets[a.label]=d};
Cgraphit.prototype.dialog_new_surface=function(){if("new_surface"in this.widgets)return this.widgets.new_surface;var a=this,d=$("<div />").attr("title","New Csurface"),e=$("<div />").addClass("group group-new-surface"),f=new Cparameter_numeric({label:"width",bAutosave:!1,parent:this,min:1,max:1920,step:1,def:400}),h=new Cparameter_numeric({label:"height",parent:this,bAutosave:!1,min:1,max:1280,step:1,def:400});e.append(f.dom_get(),h.dom_get());d.append(e);d.dialog({modal:!1,closeOnEscape:!0,stack:!0,
zIndex:10,buttons:{Ok:function(){var d=$(this).parent();a.send_trigger("create_surface",{width:d.find(".width input").attr("value"),height:d.find(".height input").attr("value")})},Cancel:function(){$(this).dialog("close")}}});return this.widgets.new_surface=d};
Cgraphit.prototype.surface_create=function(a){var d=this;a.parent=this;var e=null;try{e=new Csurface_workspace(a)}catch(f){return this.intercept(f),console.error("Cannot create surface, Exception <<< ",f," >>>"),!1}this.bind_trigger(e.cSurface,"surface_selected",function(a,e){e instanceof Csurface||d.exception("invalid_surface_selected_parameter");e.attach_graphit(d);d.selected=e});widget_factory(e.dom_get(),{width:parseInt(a.width)+100});this.surfaces.push(e);this.selected||(this.selected=e);this.dom_build_add_surface(e);
return!0};
Cgraphit.prototype.dom_build_add_surface=function(a){var d=this,e=$('<div class="group group-graphit-surface" />'),f=new Ccanvas({width:50,height:50}),h=a.cSurface;h.canvas_preview=f;f.copy({src:h.cCanvas});e.append(f.dom_get());this.rootElm.find(".group-graphit-surfaces").append(e);h.bind_trigger(h,"redraw_preview",function(a,d){h.canvas_preview.copy({src:d.cCanvas,resize:!0})});e.click(function(){h.send_trigger("surface_selected",h);cEach(d.surfaces,function(a,d){d.cSurface==h&&d.rootElm.parent().dialog("open").dialog("moveToTop")});$(this).parent().find(".group-graphit-surface").removeClass("selected");
$(this).addClass("selected")});return this};
Cgraphit.prototype.dom_build=function(){var a=$("<div />"),d=$('<div class="group group-menu" />');d.append(this.cMenu.dom_get());a.append(d);d=$('<div class="group group-graphit-surfaces"/>');cEach(this.surfaces,function(a,e){var i=$('<div class="graphit-surface" />'),j=new Ccanvas({width:50,height:50});j.copy(e.cCanvas,!0);i.append(j.dom_get());d.append(i)});a.append(d);var e=$('<div class="group group-badge">');e.append('<a href="#http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:44px;height:16px"    src="/images/w3-vcss.gif"    alt="Valid CSS!" /></a>');e.append('<a href="#http://www.w3.org/html/logo"><img src="/images/HTML5_Logo_32.png" width="32" height="32" alt="HTML5 Powered with Graphics, 3D &amp; Effects, Multimedia, and Performance &amp; Integration" title="HTML5 Powered with Graphics, 3D &amp; Effects, Multimedia, and Performance &amp; Integration"></a>');
a.append(e);this.rootElm=a;return this};Cgraphit.prototype.list=function(a){for(var d=0;d<this.surfaces.length;d++)a.call(this,d,this.surfaces[d]);return this.surfaces.length};function CgraphitAuth(a){a=a||{};a.className="CgraphitAuth";a.label="CgraphitAuth";a.disable=void 0!=a.disable?a.disable:!1;this.__init_singleton(a)}CgraphitAuth.prototype.__init_singleton=function(a){"__data"in CgraphitAuth||(CgraphitAuth.__data={});"__disable"in CgraphitAuth||(CgraphitAuth.__disable=a.disable)};CgraphitAuth.prototype.is_disable=function(){return CgraphitAuth.__disable};CgraphitAuth.prototype.set=function(a,d){console.log("set",a,d);CgraphitAuth.__data[a]=d};
CgraphitAuth.prototype.get=function(a){return!(a in CgraphitAuth.__data)?(console.warn("key doesn't exists",a),null):CgraphitAuth.__data[a]};CgraphitAuth.prototype.each=function(a){if(!a||"function"!=typeof a)throw"invalid_callback";for(var d in CgraphitAuth.__data)a.call(CgraphitAuth.__data,d,this.get(d))};CgraphitAuth.prototype.dom_get=function(a){return this.rootElm&&(void 0==a||!a)?this.rootElm:this.dom_build().rootElm};
CgraphitAuth.prototype.dom_build=function(){var a=$('<div title="Graphit Authentication" />');a.addClass("group group-graphit-authentication");var d=$('<iframe id="graphit-authentication-iframe" />');d.attr("src","/php/GoogleIdentity/index.php");d.addClass("group group-graphit-authentication-iframe");d.attr("width","100%");d.attr("height","100%");d.css("overflow","visible");a.append(d);this.rootElm=a;return this};var cGraphit,cPo,T,cGraphitAuth;
function _ok_to_build(){console.log("Language",getLanguage());cGraphitAuth=new CgraphitAuth({disable:!SHOJS_AUTH});cGraphitAuth.is_disable()||cGraphitAuth.dom_get().dialog({width:800,height:600});cPo=new Cpo({lang:getLanguage()});T=function(a){return cPo.get(a)};cGraphit=new Cgraphit;widget_factory(cGraphit.dom_get(),{width:300,position:"left top"});$(function(){$(this).bind("contextmenu",function(a){a.preventDefault()})});cEach([],function(a,d){new Cfile_GBR({src:"brushes/"+d+".gbr",callback_success:function(){console.log("[",
a,"] File loaded: "+this.src);this.dom_get().attr("title","["+this.header("bytes")+"] "+this.name).dialog({width:this.cCanvas.get_width(),height:this.cCanvas.get_height()})},callback_error:function(a){console.log("error binary file",a)}})});$(document).bind("shojs-cgrapher-grapher-error",function(a,d){console.log("bind",a,d);if("no-tool-selectionned"!=d)return!1;var e=$('<div class="dialog-error" title="Select tool first!">');e.append("<p>You must select a tool before drawing onto surface</p>");e.dialog({modal:!0,
resizable:!1,buttons:{Ok:function(){$(this).dialog("close")}}})})}
$(document).ready(function(){if(isCanvasSupported())try{_ok_to_build()}catch(a){widget_exception(a)}else{var d=$(document.createElement("div"));d.attr("title","HTML5 error");d.addClass("error");d.append("<p>Your internet browser doesn't support <b>canvas</b> element.<br><b>canvas</b> is part of HTML 5 specification<br> Browser who must support it are Chrome, Firefox, Safari</p>");d.dialog({modal:!0,close:function(){console.log("close");$("body").empty();document.location="http://github.com/shojs/graphit"}})}});
